-- 012_chat.sql
--
-- Donor ↔ campaign-owner (beneficiary) consent-based chat.
--
-- A thread is opened by either side (donor from a donation's detail, or the
-- beneficiary from their "campaign donations" list). It starts 'pending' and
-- only becomes 'active' once the other party accepts from their Alerts tab.
-- Once active, the donor, the campaign owner, and ANY admin (as "support")
-- can post messages. There is exactly ONE thread per (donor, owner) pair —
-- all donations between the same two people share it.

CREATE TABLE IF NOT EXISTS chat_threads (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  owner_user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- The campaign that prompted the chat (context only; uniqueness is on the
  -- pair, not the campaign). NULL-able so a thread survives campaign deletion.
  campaign_id      INTEGER REFERENCES campaigns(id) ON DELETE SET NULL,
  -- Lifecycle: pending (awaiting accept) | active | declined.
  status           VARCHAR(16) NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending','active','declined')),
  -- Who opened the request — so the recipient (the OTHER user) is the one who
  -- must accept, and so we can tell the initiator "your request was accepted".
  initiated_by     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- One ongoing conversation per donor + owner pair.
  CONSTRAINT uq_chat_pair UNIQUE (donor_user_id, owner_user_id)
);

CREATE INDEX IF NOT EXISTS idx_chat_threads_donor ON chat_threads (donor_user_id);
CREATE INDEX IF NOT EXISTS idx_chat_threads_owner ON chat_threads (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_chat_threads_status ON chat_threads (status);

CREATE TABLE IF NOT EXISTS chat_messages (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id      BIGINT  NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
  sender_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Snapshot of the sender's role at send time (1 donor, 2 beneficiary,
  -- 3 volunteer, 0/other = admin-support). Lets the UI label bubbles without
  -- a join, and stays correct even if the user's role later changes.
  sender_role    INTEGER NOT NULL DEFAULT 0,
  body           TEXT    NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_thread ON chat_messages (thread_id, id);

-- Per-user read cursor: the id of the last message a participant has seen in a
-- thread. Drives unread badges without a row-per-message read table.
CREATE TABLE IF NOT EXISTS chat_reads (
  thread_id        BIGINT  NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
  user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_msg_id BIGINT  NOT NULL DEFAULT 0,
  PRIMARY KEY (thread_id, user_id)
);
