-- 013_app_events.sql
--
-- Activity / analytics event log — the Postgres home for what used to be the
-- Firestore `events` collection. The mobile app logs an append-only row for
-- meaningful actions (login, register, donation_submit, support_ticket_submit,
-- notification_mark_read, …) and the admin dashboard's live "events feed" reads
-- the most recent rows (polled, ordered by created_at_ms desc).
--
-- Field names mirror exactly what the app wrote to Firestore and what the admin
-- feed consumes, so neither side needs a field-mapping shim.

CREATE TABLE IF NOT EXISTS app_events (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_type      VARCHAR(64)  NOT NULL,
  event_label     TEXT,
  module          VARCHAR(64),
  action          VARCHAR(64),
  status          VARCHAR(32)  NOT NULL DEFAULT 'success',
  source          VARCHAR(32)  NOT NULL DEFAULT 'app',

  -- Actor (kept denormalised so the feed renders without a join, and survives
  -- user deletion — this is an audit log).
  user_id         INTEGER,
  role_id         INTEGER,
  name            TEXT,
  number          TEXT,
  number_digits   TEXT,

  -- Targets the event references (entity_id = primary record, target_id =
  -- secondary, e.g. a donation's campaign).
  entity_id       BIGINT,
  target_id       BIGINT,

  -- Money-event extras.
  amount          NUMERIC,
  currency        VARCHAR(8),
  payment_method  VARCHAR(32),

  content_locale  VARCHAR(16),
  note            TEXT,
  metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,

  -- Admin-side flags (the feed hides read notification rows by default).
  is_read         BOOLEAN      NOT NULL DEFAULT FALSE,
  admin_state     VARCHAR(32),

  -- created_at is the server truth; created_at_ms is the client epoch-ms the
  -- app sends, preserved so ordering matches what the old Firestore feed used.
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  created_at_ms   BIGINT       NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint
);

-- The feed reads "latest N, newest first".
CREATE INDEX IF NOT EXISTS idx_app_events_created_at_ms ON app_events (created_at_ms DESC);
CREATE INDEX IF NOT EXISTS idx_app_events_event_type ON app_events (event_type);
