-- 015_permissions.sql
--
-- Phase 6 — staff permission tiers + an editable permission matrix.
--
-- Two "role" concepts are kept separate on purpose:
--   • role_id     = the APP user's role (donor / beneficiary / volunteer /
--                   employee / none) — unchanged, drives the mobile app.
--   • staff_tier  = the DASHBOARD access tier introduced here:
--                     super_admin > admin > supervisor > employee > user
--
-- The permission check uses sensible code-level defaults per tier; rows in
-- role_permissions OVERRIDE those defaults (grant or revoke) so the Super Admin
-- can tune access per module/action from the Permissions UI without a deploy.

-- 1) Staff tier ---------------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS staff_tier VARCHAR(20) NOT NULL DEFAULT 'user';

-- Legacy is_admin=1 accounts become the 'admin' tier.
UPDATE users SET staff_tier = 'admin'
 WHERE is_admin = 1 AND staff_tier = 'user';

-- The canonical dashboard account (username 'admin') is the root Super Admin.
UPDATE users SET staff_tier = 'super_admin'
 WHERE username = 'admin';

-- 2) Editable permission overrides -------------------------------------------
-- Only rows that DIFFER from the code default are stored. action is one of:
--   view | add | edit | archive | delete | export
-- module is a dashboard resource slug (users, donations, beneficiary, …).
CREATE TABLE IF NOT EXISTS role_permissions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tier       VARCHAR(20) NOT NULL,
  module     VARCHAR(64) NOT NULL,
  action     VARCHAR(20) NOT NULL,
  allowed    BOOLEAN     NOT NULL,
  updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tier, module, action)
);
CREATE INDEX IF NOT EXISTS idx_role_permissions_tier ON role_permissions (tier);

-- 3) Immutable permission-change ledger (A-13) --------------------------------
-- Every change to role_permissions or a user's staff_tier is stamped here with
-- who/when/from-where. Append-only: the app never UPDATEs or DELETEs these rows.
CREATE TABLE IF NOT EXISTS permission_audit_log (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    INTEGER,
  action      VARCHAR(64) NOT NULL,   -- e.g. 'permission_set', 'tier_change'
  target      VARCHAR(128),           -- e.g. 'supervisor/donations/delete' or 'user#42'
  old_value   TEXT,
  new_value   TEXT,
  ip_address  VARCHAR(64),
  created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_permission_audit_created ON permission_audit_log (created_at DESC);
