-- 020_custom_professions.sql
--
-- Section 13 — admin-added volunteer professions/skills. The base 28-key
-- catalogue lives in code (volunteers/catalogue.go); this table lets the
-- Primary Administrator add extra professions from the dashboard without a
-- deploy. Custom keys are registered into the skill validator at startup so a
-- volunteer can be tagged with them just like a built-in skill.
--
--   skill_key — canonical slug (e.g. 'welder'); unique, lowercased.
--   category  — one of the catalogue category slugs (or 'custom').
--   label_*   — the display name in each supported language.
CREATE TABLE IF NOT EXISTS custom_professions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_key  VARCHAR(64)  NOT NULL UNIQUE,
  category   VARCHAR(32)  NOT NULL DEFAULT 'custom',
  label_en   VARCHAR(120) NOT NULL,
  label_ar   VARCHAR(120) NOT NULL DEFAULT '',
  label_ckb  VARCHAR(120) NOT NULL DEFAULT '',
  label_kmr  VARCHAR(120) NOT NULL DEFAULT '',
  created_by INTEGER,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
