-- 029 — Project-category CMS (#17).
--
-- An admin-managed, ordered, 4-language list of project categories. The
-- beneficiary picks one from a dropdown when submitting a project (instead of
-- typing free text); the picked category's localized names are snapshotted into
-- the existing beneficiary_project_requests.category(_ar/_sorani/_badini)
-- columns, so nothing about existing projects changes. Mirrors the
-- custom_professions CMS pattern (Section 13): name_en/ar/ckb/kmr + display_order.
CREATE TABLE IF NOT EXISTS project_categories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed a starter set (admin-editable afterwards). Idempotent.
INSERT INTO project_categories (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('water',      'Water',        'مياه',        'ئاو',            'ئاڤ',              1),
  ('health',     'Health',       'صحة',         'تەندروستی',      'تەندرستی',         2),
  ('education',  'Education',     'تعليم',       'پەروەردە',       'پەروەردە',         3),
  ('shelter',    'Shelter',      'مأوى',        'پەناگە',         'حەوانگەه',         4),
  ('food',       'Food',         'غذاء',        'خۆراک',          'خوارن',            5),
  ('livelihood', 'Livelihood',   'سبل العيش',   'بژێوی ژیان',     'بژیڤ',             6),
  ('emergency',  'Emergency',    'طوارئ',       'فریاگوزاری',     'فریاکەفتن',        7),
  ('orphans',    'Orphans',      'أيتام',       'هەتیوان',        'سێوی',             8),
  ('medical',    'Medical care', 'رعاية طبية',  'چاودێری پزیشکی', 'چاودێریا پزیشکی',  9),
  ('other',      'Other',        'أخرى',        'هیتر',           'دی',              10)
ON CONFLICT (slug) DO NOTHING;
