-- 030 — Payment-method scalability (#19).
--
-- Admin-managed donation payment methods (banks / cash / wallets) with their
-- account details, replacing the two hardcoded app options (Cash + FIB). The
-- app fetches active methods for the donate screen; the org can add unlimited
-- methods. Mirrors the project_categories CMS (#17) with extra per-method
-- fields (account number/name, method_type, localized instructions).
CREATE TABLE IF NOT EXISTS payment_methods (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug             VARCHAR(64)  NOT NULL UNIQUE,
  method_type      VARCHAR(16)  NOT NULL DEFAULT 'bank',   -- cash | bank | wallet
  name_en          VARCHAR(120) NOT NULL,
  name_ar          VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb         VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr         VARCHAR(120) NOT NULL DEFAULT '',
  instructions_en  TEXT         NOT NULL DEFAULT '',
  instructions_ar  TEXT         NOT NULL DEFAULT '',
  instructions_ckb TEXT         NOT NULL DEFAULT '',
  instructions_kmr TEXT         NOT NULL DEFAULT '',
  account_number   VARCHAR(120) NOT NULL DEFAULT '',
  account_name     VARCHAR(160) NOT NULL DEFAULT '',
  display_order    INTEGER      NOT NULL DEFAULT 0,
  active           SMALLINT     NOT NULL DEFAULT 1,
  created_by       INTEGER,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed the two existing methods (preserving the FIB account number). Idempotent.
INSERT INTO payment_methods
  (slug, method_type, name_en, name_ar, name_ckb, name_kmr,
   instructions_en, instructions_ar, instructions_ckb, instructions_kmr,
   account_number, display_order) VALUES
  ('cash', 'cash', 'Cash', 'نقداً', 'نەقد', 'نەقد',
   'Pay in person or at a collection point.', 'ادفع شخصياً أو في نقطة تجميع.',
   'بە کەسی خۆت یان لە خاڵێکی کۆکردنەوە بیدە.', 'ب خۆ یان ل خالەکا کۆمکرنێ بدە.',
   '', 1),
  ('fib', 'bank', 'FIB', 'FIB', 'FIB', 'FIB',
   'First Iraqi Bank and supported channels.', 'المصرف العراقي الأول والقنوات المدعومة.',
   'یەکەم بانکی عێراقی و کەناڵە پشتگیریکراوەکان.', 'بانکێ ئێراقی یێ ئێکێ و کەناڵێن پشتەڤانیکری.',
   '7510208962', 2)
ON CONFLICT (slug) DO NOTHING;
