-- 032 — "Our Work" media-category CMS (#22).
--
-- An admin-managed, ordered, 4-language taxonomy for the News & Activities
-- ("Our Work") feed. Each media post can be tagged with one category_slug; the
-- app shows category filter chips and a category label per post. Mirrors the
-- project_categories CMS (029): name_en/ar/ckb/kmr + display_order + active.
CREATE TABLE IF NOT EXISTS media_categories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed the starter set of 10 "Our Work" categories (admin-editable afterwards).
-- Idempotent via ON CONFLICT on the unique slug.
INSERT INTO media_categories (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('relief',      'Emergency Relief',      'الإغاثة الطارئة',    'فریاگوزاری',            'فریاکەفتن',              1),
  ('food',        'Food Aid',              'المساعدات الغذائية', 'یارمەتیی خۆراک',        'یارمەتیا خوارنێ',        2),
  ('water',       'Water & Sanitation',    'المياه والإصحاح',    'ئاو و خاوێنکاری',       'ئاڤ و پاقژی',           3),
  ('health',      'Healthcare',            'الرعاية الصحية',     'چاودێری تەندروستی',     'چاودێریا تەندرستیێ',    4),
  ('education',   'Education',             'التعليم',            'پەروەردە',              'پەروەردە',              5),
  ('orphans',     'Orphan Care',           'رعاية الأيتام',      'چاودێری هەتیوان',       'چاودێریا سێویان',       6),
  ('shelter',     'Shelter',               'الإيواء',            'پەناگە',                'حەوانگەه',              7),
  ('winter',      'Winter Campaign',       'حملة الشتاء',        'هەڵمەتی زستان',         'کەمپینا زڤستانێ',       8),
  ('ramadan',     'Ramadan Campaign',      'حملة رمضان',         'هەڵمەتی ڕەمەزان',       'کەمپینا ڕەمەزانێ',      9),
  ('development', 'Community Development',  'تنمية المجتمع',      'گەشەپێدانی کۆمەڵگا',    'پێشڤەبرنا جڤاکێ',      10)
ON CONFLICT (slug) DO NOTHING;

-- Tag column on posts. Nullable (a post may be uncategorized); free VARCHAR so a
-- category delete never breaks existing posts (they keep the slug text, just
-- drop out of the filter chips). Indexed for the per-category feed filter.
ALTER TABLE media_posts
  ADD COLUMN IF NOT EXISTS category_slug VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_media_posts_category
  ON media_posts (category_slug)
  WHERE category_slug IS NOT NULL;
