-- 034 — Post engagement: likes, comments, banned-words (#24 + #25).
--
-- Adds social engagement to the News & Activities feed (media_posts):
--   * post_likes    — one row per (post, user); a like is a toggle.
--   * post_comments — user comments with a moderation status. Clean comments
--     land 'approved' (visible); comments containing a banned word land
--     'pending' + flagged (held for admin review). Admins can 'hidden' any.
--   * banned_words  — admin-managed blocklist checked at comment-submit time.
--   * media_posts.share_count — incremented when a user shares a post (#24).
--
-- All idempotent (IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS post_likes (
  post_id    BIGINT    NOT NULL,
  user_id    INTEGER   NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_post_likes_post ON post_likes (post_id);

CREATE TABLE IF NOT EXISTS post_comments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    BIGINT      NOT NULL,
  user_id    INTEGER     NOT NULL,
  body       TEXT        NOT NULL,
  status     VARCHAR(16) NOT NULL DEFAULT 'approved'
             CHECK (status IN ('pending','approved','hidden')),
  flagged    SMALLINT    NOT NULL DEFAULT 0,  -- 1 = matched a banned word
  created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_post_comments_post ON post_comments (post_id, status);
CREATE INDEX IF NOT EXISTS idx_post_comments_status ON post_comments (status);

CREATE TABLE IF NOT EXISTS banned_words (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word       VARCHAR(100) NOT NULL UNIQUE,  -- stored lowercased
  created_by INTEGER,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE media_posts
  ADD COLUMN IF NOT EXISTS share_count INTEGER NOT NULL DEFAULT 0;
