-- 036 — Marketplace: category CMS + SKU + specs + labels (#28).
--
-- #28 adds:
--   * marketplace_categories — an admin-managed 4-language category taxonomy
--     (clone of media_categories); products tag with category_slug.
--   * marketplace_products.sku    — stock-keeping unit (free text).
--   * marketplace_products.specs  — free-text spec sheet, one "Key: Value" per
--     line (the app splits it into rows). Simpler than JSONB, still useful.
--   * marketplace_products.labels — TEXT[] of badges from a fixed enum
--     (new / sale / featured / used / in_stock).
--
-- The existing free-text `category` column is kept for backward compatibility;
-- category_slug is the new CMS-driven field the app filters on.
--
-- All idempotent.

CREATE TABLE IF NOT EXISTS marketplace_categories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO marketplace_categories (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('clothing',    'Clothing',         'الملابس',        'جلوبەرگ',           'جلک',                1),
  ('food',        'Food',             'المواد الغذائية', 'خۆراک',             'خوارن',              2),
  ('furniture',   'Furniture',        'الأثاث',         'کەلوپەلی ماڵ',      'قەرەبالغی مالێ',    3),
  ('electronics', 'Electronics',      'الإلكترونيات',   'ئەلیکترۆنیات',      'ئەلیکترۆنیک',        4),
  ('appliances',  'Home appliances',  'الأجهزة المنزلية','ئامێری ماڵ',        'ئامیرێن مالێ',       5),
  ('kitchenware', 'Kitchenware',      'أدوات المطبخ',   'کەرەستەی چێشتخانە', 'ئامیرێن پێژگەهێ',   6),
  ('kids',        'Kids & baby',      'الأطفال',        'منداڵان',           'زاڕۆک',              7),
  ('footwear',    'Footwear',         'الأحذية',        'پێڵاو',             'پێلاڤ',              8),
  ('medical',     'Medical supplies', 'المستلزمات الطبية','پێداویستی پزیشکی', 'پێدڤیێن پزیشکی',    9),
  ('tools',       'Tools',            'الأدوات',        'ئامرازەکان',        'ئامراز',            10),
  ('books',       'Books',            'الكتب',          'کتێب',              'پەرتوک',            11),
  ('other',       'Other',            'أخرى',           'هیتر',              'دی',                12)
ON CONFLICT (slug) DO NOTHING;

ALTER TABLE marketplace_products
  ADD COLUMN IF NOT EXISTS category_slug VARCHAR(64),
  ADD COLUMN IF NOT EXISTS sku           VARCHAR(128),
  ADD COLUMN IF NOT EXISTS specs         TEXT,
  ADD COLUMN IF NOT EXISTS labels        TEXT[] NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_marketplace_products_category
  ON marketplace_products (category_slug)
  WHERE category_slug IS NOT NULL;
