-- 037 — City Guide sectors + hours + gallery (#29).
--
-- Two parts:
--   1. city_sectors — an admin-managed, ordered, 4-language taxonomy the City
--      Guide is organised by (filter chips in the app). Mirrors the
--      project_categories / media_categories CMS pattern (slug + name_en/ar/
--      ckb/kmr + display_order + active). Seeded with 6 starter sectors,
--      admin-editable afterwards.
--   2. Extend city_directory_entries with the per-place extras #29 adds:
--      sectors (which sectors a place belongs to), 4-language opening hours,
--      and a photo gallery (reuses the #23 gallery TEXT[] convention).
--
-- Idempotent: CREATE ... IF NOT EXISTS, seed ON CONFLICT DO NOTHING, and
-- ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS city_sectors (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed 6 starter sectors (admin-editable afterwards). Idempotent.
INSERT INTO city_sectors (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('healthcare', 'Healthcare',          'الرعاية الصحية',   'چاودێری تەندروستی', 'چاودێریا تەندرستیێ', 1),
  ('education',  'Education',            'التعليم',          'پەروەردە',          'پەروەردە',           2),
  ('government', 'Government & Services','الدوائر والخدمات', 'نووسینگە و خزمەت',   'نڤیسینگەه و خزمەت',   3),
  ('markets',    'Markets & Shops',      'الأسواق والمحلات', 'بازاڕ و دووکان',    'بازار و دوکان',      4),
  ('worship',    'Places of Worship',    'دور العبادة',      'شوێنی پەرستن',      'جهێن پەرستنێ',       5),
  ('relief',     'Relief & Emergency',   'الإغاثة والطوارئ', 'فریاگوزاری و فریاکەوتن', 'هاریکاری و فریاکەفتن', 6)
ON CONFLICT (slug) DO NOTHING;

-- Per-place extras on the existing directory table. The table uses the
-- _ar/_sorani/_badini suffix convention (not _ckb/_kmr), so opening hours
-- follow it for consistency with name_/description_.
ALTER TABLE city_directory_entries
  ADD COLUMN IF NOT EXISTS sectors               TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS opening_hours         TEXT,
  ADD COLUMN IF NOT EXISTS opening_hours_ar      TEXT,
  ADD COLUMN IF NOT EXISTS opening_hours_sorani  TEXT,
  ADD COLUMN IF NOT EXISTS opening_hours_badini  TEXT,
  ADD COLUMN IF NOT EXISTS gallery               TEXT[] NOT NULL DEFAULT '{}';

-- GIN index so a sector-filtered City Guide query (sectors @> ARRAY[slug])
-- stays fast as the directory grows.
CREATE INDEX IF NOT EXISTS idx_city_directory_sectors ON city_directory_entries USING GIN (sectors);
