-- 046 — Marriage search: save + request-meeting (#46). Two small tables on top
-- of the existing marriage_profiles. Idempotent.

-- A user's saved (bookmarked) profiles.
CREATE TABLE IF NOT EXISTS marriage_saved (
  user_id    INTEGER NOT NULL,
  profile_id BIGINT  NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, profile_id)
);
CREATE INDEX IF NOT EXISTS idx_marriage_saved_user ON marriage_saved (user_id);

-- Meeting requests a user sends about a profile (staff mediate).
CREATE TABLE IF NOT EXISTS marriage_meeting_requests (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id INTEGER NOT NULL,
  profile_id   BIGINT  NOT NULL,
  message      TEXT,
  status       VARCHAR(16) NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','approved','declined')),
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_marriage_meet_from ON marriage_meeting_requests (from_user_id);
CREATE INDEX IF NOT EXISTS idx_marriage_meet_profile ON marriage_meeting_requests (profile_id);
