-- 048 — Digital aid-delivery receipts with photos (#50). Staff record a
-- delivery (items + proof photos + recipient); the recipient views it in the
-- app. Idempotent.
CREATE TABLE IF NOT EXISTS aid_receipts (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_code      VARCHAR(64) NOT NULL UNIQUE,
  recipient_user_id INTEGER,               -- the app user who received the aid
  recipient_name    VARCHAR(200),
  items             TEXT,                  -- what was delivered
  delivered_at      TIMESTAMP,
  delivered_by      VARCHAR(200),          -- staff / volunteer name
  photos            TEXT[] NOT NULL DEFAULT '{}',
  notes             TEXT,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_aid_receipts_recipient ON aid_receipts (recipient_user_id);
