-- 058 — Note #35 (part 1): a marriage "meeting request" used to be a dead
-- end — INSERT INTO marriage_meeting_requests and nothing ever read it again.
-- This adds a genuine staff-mediated chat: when staff APPROVE a meeting
-- request, a marriage_chat_threads row opens between the requester and the
-- profile owner; the profile owner must then accept it (same pending→active
-- lifecycle as the existing donor↔owner chat_threads, migration 012) before
-- either side can post. Unlike that chat, this one is privacy-first per the
-- client's spec (ID-code privacy): messages are stored with a sender_role
-- ('requester'|'owner'|'staff') rather than resolved to a real identity for
-- mobile responses, so the app layer can mask who's on the other end — the
-- masking logic lives in Go (internal/marriagechat), not in this schema.

ALTER TABLE marriage_meeting_requests
  ADD COLUMN IF NOT EXISTS thread_id BIGINT,
  ADD COLUMN IF NOT EXISTS decided_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS decided_by INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS marriage_chat_threads (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_request_id BIGINT NOT NULL REFERENCES marriage_meeting_requests(id) ON DELETE CASCADE,
  profile_id         BIGINT NOT NULL REFERENCES marriage_profiles(id) ON DELETE CASCADE,
  requester_user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  owner_user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- pending (awaiting the profile owner's accept) | active | declined.
  status             VARCHAR(16) NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','active','declined')),
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_marriage_chat_pair UNIQUE (requester_user_id, profile_id)
);

ALTER TABLE marriage_meeting_requests
  ADD CONSTRAINT fk_marriage_meeting_requests_thread
  FOREIGN KEY (thread_id) REFERENCES marriage_chat_threads(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_marriage_chat_threads_requester ON marriage_chat_threads (requester_user_id);
CREATE INDEX IF NOT EXISTS idx_marriage_chat_threads_owner ON marriage_chat_threads (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_marriage_chat_threads_status ON marriage_chat_threads (status);

CREATE TABLE IF NOT EXISTS marriage_chat_messages (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id      BIGINT NOT NULL REFERENCES marriage_chat_threads(id) ON DELETE CASCADE,
  sender_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Who's speaking, from the OTHER non-staff party's point of view — never a
  -- real name for 'requester'/'owner'. 'staff' covers any admin relaying.
  sender_role    VARCHAR(16) NOT NULL CHECK (sender_role IN ('requester','owner','staff')),
  body           TEXT NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_marriage_chat_messages_thread ON marriage_chat_messages (thread_id, id);

CREATE TABLE IF NOT EXISTS marriage_chat_reads (
  thread_id        BIGINT NOT NULL REFERENCES marriage_chat_threads(id) ON DELETE CASCADE,
  user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_msg_id BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (thread_id, user_id)
);

DROP TRIGGER IF EXISTS trg_marriage_chat_threads_updated_at ON marriage_chat_threads;
CREATE TRIGGER trg_marriage_chat_threads_updated_at
  BEFORE UPDATE ON marriage_chat_threads
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
