-- 059 — Note #36, part 1: the donor↔beneficiary chat lets ANY admin reply as
-- an anonymous "Support" role — there's no specific, named "Responsible
-- Staff Member" a donor/beneficiary can see. Adds an assignment column: a
-- thread can be "claimed" by one staff member, who then shows by their real
-- name (instead of generic "Support") to both parties — the display-layer
-- change lives in Go/Flutter, this just adds the column that tracks it.
-- Nullable/optional: an unclaimed thread behaves exactly as before.
ALTER TABLE chat_threads
  ADD COLUMN IF NOT EXISTS assigned_staff_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_chat_threads_assigned_staff ON chat_threads (assigned_staff_user_id);

-- Note #36, part 2: "Operational Administrative Chats" — Manager ↔ Staff
-- Member. Any two dashboard (staff_tier != 'user') accounts can message each
-- other directly; unlike the donor chat there's no accept/decline step
-- (both parties are already trusted staff) — a thread is created active on
-- the first message. One thread per unordered pair, enforced by always
-- storing the lower user id first.
CREATE TABLE IF NOT EXISTS staff_chat_threads (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_a_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  user_b_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_staff_chat_pair_ordered CHECK (user_a_id < user_b_id),
  CONSTRAINT uq_staff_chat_pair UNIQUE (user_a_id, user_b_id)
);

CREATE INDEX IF NOT EXISTS idx_staff_chat_threads_a ON staff_chat_threads (user_a_id);
CREATE INDEX IF NOT EXISTS idx_staff_chat_threads_b ON staff_chat_threads (user_b_id);

CREATE TABLE IF NOT EXISTS staff_chat_messages (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id      BIGINT NOT NULL REFERENCES staff_chat_threads(id) ON DELETE CASCADE,
  sender_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body           TEXT NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_staff_chat_messages_thread ON staff_chat_messages (thread_id, id);

CREATE TABLE IF NOT EXISTS staff_chat_reads (
  thread_id        BIGINT NOT NULL REFERENCES staff_chat_threads(id) ON DELETE CASCADE,
  user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_msg_id BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (thread_id, user_id)
);

DROP TRIGGER IF EXISTS trg_staff_chat_threads_updated_at ON staff_chat_threads;
CREATE TRIGGER trg_staff_chat_threads_updated_at
  BEFORE UPDATE ON staff_chat_threads
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
