-- 061 — Note #36, part 3: the Staff↔Volunteer↔Beneficiary chat. Anchored on
-- the volunteer-to-case link added in migration 060: once a signup is both
-- linked to a beneficiary case AND approved (or further along), a 3-way
-- thread opens between the volunteer, the case's beneficiary, and staff
-- (any admin may relay as "Support"/claim it as the named responsible staff
-- member, same pattern as migration 059's donor↔beneficiary chat upgrade).
--
-- Unlike the marriage chat (migration 058), identities are NOT masked here —
-- this is operational coordination (e.g. delivering aid), so the volunteer
-- and beneficiary need to actually know who they're each talking to.
--
-- One thread per signup (a volunteer helping the same case on a second
-- mission gets a second signup, and a fresh thread — kept simple rather than
-- merging across missions).

CREATE TABLE IF NOT EXISTS case_volunteer_chat_threads (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signup_id           BIGINT NOT NULL UNIQUE REFERENCES volunteer_mission_signups(id) ON DELETE CASCADE,
  case_id             BIGINT NOT NULL REFERENCES beneficiary_cases(id) ON DELETE CASCADE,
  volunteer_user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  beneficiary_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Claimed "Responsible Staff Member" — nullable, same pattern as
  -- chat_threads.assigned_staff_user_id (migration 059).
  assigned_staff_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_case_vol_chat_threads_volunteer ON case_volunteer_chat_threads (volunteer_user_id);
CREATE INDEX IF NOT EXISTS idx_case_vol_chat_threads_beneficiary ON case_volunteer_chat_threads (beneficiary_user_id);
CREATE INDEX IF NOT EXISTS idx_case_vol_chat_threads_case ON case_volunteer_chat_threads (case_id);

CREATE TABLE IF NOT EXISTS case_volunteer_chat_messages (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id      BIGINT NOT NULL REFERENCES case_volunteer_chat_threads(id) ON DELETE CASCADE,
  sender_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Snapshot of the sender's part in this thread at send time — mirrors
  -- chat_messages.sender_role's "0 = support" convention but named, since
  -- there are 3 distinct roles here instead of donor/owner + admin.
  sender_role    VARCHAR(16) NOT NULL CHECK (sender_role IN ('volunteer','beneficiary','staff')),
  body           TEXT NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_case_vol_chat_messages_thread ON case_volunteer_chat_messages (thread_id, id);

CREATE TABLE IF NOT EXISTS case_volunteer_chat_reads (
  thread_id        BIGINT NOT NULL REFERENCES case_volunteer_chat_threads(id) ON DELETE CASCADE,
  user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_msg_id BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (thread_id, user_id)
);

DROP TRIGGER IF EXISTS trg_case_vol_chat_threads_updated_at ON case_volunteer_chat_threads;
CREATE TRIGGER trg_case_vol_chat_threads_updated_at
  BEFORE UPDATE ON case_volunteer_chat_threads
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
