-- 065_wallet.sql
-- Note #42 (Section One — "Financial Wallet") — a TEST-phase internal app
-- wallet. Each real user (not guests — nothing in the app credits a guest
-- wallet) gets a stored IQD balance. For now the ONLY way to add funds is an
-- admin manually crediting a user from the dashboard (no payment-gateway
-- top-up yet); the balance can then be spent as a payment method on
-- donations and marketplace purchases.
--
-- wallet_balance_iqd is a plain integer count of whole Iraqi Dinars (IQD has
-- no meaningful fractional unit in this app's existing amount fields either).
--
-- wallet_transactions is the ledger: every balance change (topup, donation
-- debit, purchase debit, or a refund when a debited action fails) gets a
-- row, so the balance is always explainable/auditable, not just a bare
-- number an admin can silently edit.

ALTER TABLE users ADD COLUMN IF NOT EXISTS wallet_balance_iqd BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS wallet_transactions (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Positive = credit (topup/refund), negative = debit (donation/purchase).
  amount_iqd          BIGINT NOT NULL,
  type                VARCHAR(20) NOT NULL CHECK (type IN ('topup', 'donation', 'purchase', 'refund')),
  related_entity_type VARCHAR(64),
  related_entity_id   BIGINT,
  note                TEXT,
  -- The admin who performed a topup; NULL for a system-generated debit/refund.
  created_by          INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_user ON wallet_transactions (user_id, id DESC);
