-- 071 — Beneficiary case categories: Quick Filter Capsules (client spec,
-- Home screen "Section Three").
--
-- An admin-managed, ordered, 4-language taxonomy for beneficiary cases
-- (Orphan Sponsorship, Widow Support, Food Baskets, etc.). Each case can be
-- tagged with one category_slug; the app shows capsule filter chips on Home
-- that jump into the case list pre-filtered. Mirrors the media_categories
-- CMS pattern (032) exactly.
CREATE TABLE IF NOT EXISTS case_categories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed a starter set matching the client's examples (admin-editable afterwards).
-- Idempotent via ON CONFLICT on the unique slug.
INSERT INTO case_categories (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('orphan_sponsorship', 'Orphan Sponsorship', 'كفالة الأيتام',       'کەفالەتی هەتیوان',      'کەفالەتا سێویان',       1),
  ('widow_support',      'Widow Support',      'دعم الأرامل',          'پشتگیری بێوەژنان',      'پشتگیریا بێوەژنان',      2),
  ('food_baskets',       'Food Baskets',       'السلال الغذائية',      'سەبەتەی خۆراک',         'سەلکێن خوارنێ',          3),
  ('medical_aid',        'Medical Aid',        'المساعدات الطبية',     'یارمەتیی پزیشکی',       'یارمەتیا دەرمانی',      4),
  ('education_support',  'Education Support',  'الدعم التعليمي',       'پشتگیری پەروەردەیی',    'پشتگیریا پەروەردەیێ',   5),
  ('housing_assistance', 'Housing Assistance',  'مساعدات السكن',        'یارمەتیی نیشتەجێبوون',  'یارمەتیا خانی',         6),
  ('emergency_relief',   'Emergency Relief',    'الإغاثة الطارئة',      'فریاگوزاری',            'فریاکەفتن',              7)
ON CONFLICT (slug) DO NOTHING;

-- Tag column on cases. Nullable (a case may be uncategorized); free VARCHAR so
-- a category delete never breaks existing cases (they keep the slug text,
-- just drop out of the capsule filter). Indexed for the per-category filter.
ALTER TABLE beneficiary_cases
  ADD COLUMN IF NOT EXISTS category_slug VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_beneficiary_cases_category
  ON beneficiary_cases (category_slug)
  WHERE category_slug IS NOT NULL;
