-- 085 — Donations Page spec, parts 4/5 and "Third"/"Fourth"/"Fifth".
--
-- Already implemented, NOT rebuilt here:
--   * "Fourth: Project Management Through the Admin Panel" — project_categories
--     (migration 029) already has slug / 4-language names / display_order /
--     active, and full admin CRUD is already routed: GET, POST (add),
--     PATCH (edit + activate/deactivate), reorder, DELETE. Showing, hiding,
--     temporarily disabling, reactivating, adding, editing and deleting a
--     project are therefore all supported without new code — this migration
--     only seeds the projects the spec names.
--   * "Enable an option for adding and naming a new field automatically
--     without creating separate code" — satisfied by that same admin CRUD:
--     a new project is a row, not a code change.
--   * Donation to support the organization — donations.donation_kind already
--     accepts 'operational'.

-- 1. "Donation to a Specific Project" — the spec's project list. These extend
--    the generic starter set from migration 029; staff can rename, reorder,
--    deactivate or delete any of them from the Admin Panel.
INSERT INTO project_categories (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('general_activities',   'General activities',        'الأنشطة العامة',         'چالاکییە گشتییەکان',    'چالاکیێن گشتی',        20),
  ('orphan_sponsorship',   'Orphan sponsorship',        'كفالة الأيتام',          'کفالەتی هەتیوان',       'کەفالەتا سێویان',      21),
  ('widow_sponsorship',    'Widow sponsorship',         'كفالة الأرامل',          'کفالەتی بێوەژنان',      'کەفالەتا بیوەژنان',    22),
  ('beneficiary_sponsor',  'Beneficiary sponsorship',   'كفالة المستفيدين',       'کفالەتی سوودمەندان',    'کەفالەتا سوودمەندان',  23),
  ('student_sponsorship',  'Student sponsorship',       'كفالة الطلبة',           'کفالەتی خوێندکاران',    'کەفالەتا خواندکاران',  24),
  ('debt_repayment',       'Debt repayment',            'سداد الديون',            'قەرزدانەوە',            'ڤەگەراندنا قەرزان',    25),
  ('eid_clothing',         'Eid clothing for children', 'كسوة العيد للأطفال',     'جلی جەژن بۆ منداڵان',   'جلکێن جەژنێ بۆ زاڕۆکان', 26),
  ('general_clothing',     'General clothing',          'الملابس العامة',         'جلوبەرگی گشتی',         'جلکێن گشتی',           27),
  ('school_supplies',      'School supplies',           'القرطاسية المدرسية',     'پێداویستی خوێندن',      'پێدڤیێن خواندنێ',      28),
  ('house_rent',           'House-rent payment',        'دفع إيجار المنزل',       'پارەی کرێی خانوو',      'پارێ کریا خانی',       29),
  ('generator_rent',       'Generator-rent payment',    'دفع إيجار المولدة',      'پارەی کرێی مۆلیدە',     'پارێ کریا مۆلیدەیێ',   30),
  ('winter_kerosene',      'Kerosene during winter',    'توفير النفط في الشتاء',  'نەوت لە زستاندا',       'نەفت د زڤستانێ دا',    31),
  ('food_baskets',         'Food baskets',              'السلال الغذائية',        'سەبەتەی خۆراک',         'سەبەتێن خوارنێ',       32),
  ('iftar_meals',          'Iftar meals',               'وجبات الإفطار',          'ژەمی ئیفتار',           'ژەمێن ئێفتارێ',        33),
  ('charitable_marriage',  'Charitable marriage support','دعم الزواج الخيري',     'پشتگیری هاوسەرگیری خێرخوازانە','پشتەڤانیا زەواجا خێرخازی', 34),
  ('household_furniture',  'Household furniture',       'الأثاث المنزلي',         'کەلوپەلی ماڵ',          'کەلوپەلێن مالێ',       35),
  ('electrical_appliances','Electrical appliances',     'الأجهزة الكهربائية',     'ئامێرە کارەباییەکان',   'ئامێرێن کارەبایی',     36),
  ('small_projects',       'Small projects',            'المشاريع الصغيرة',       'پڕۆژە بچووکەکان',       'پرۆژێن بچویک',         37),
  ('handicrafts',          'Handicrafts',               'الحرف اليدوية',          'دەستکردەکان',           'دەستکرد',              38),
  ('well_drilling',        'Well drilling',             'حفر الآبار',             'لێدانی بیر',            'کۆلانا بیران',         39),
  ('home_renovation',      'Home renovation',           'ترميم المنازل',          'نۆژەنکردنەوەی ماڵ',     'نویکرنا خانیان',       40),
  ('medical_cases',        'Medical cases',             'الحالات الطبية',         'کەیسە پزیشکییەکان',     'حالەتێن پزیشکی',       41)
ON CONFLICT (slug) DO NOTHING;

-- 2. In-kind donation categories. The in-kind flow took a free-text category,
--    so the spec's examples could not be offered as choices or managed by
--    staff. Same shape as project_categories/marketplace_categories, so the
--    admin CRUD pattern and the "add a new one without code" requirement
--    carry over.
CREATE TABLE IF NOT EXISTS inkind_categories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO inkind_categories (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('food_supplies',      'Food supplies',       'المواد الغذائية',    'پێداویستی خۆراک',    'پێدڤیێن خوارنێ',      1),
  ('clothing',           'Clothing',            'الملابس',            'جلوبەرگ',            'جلک',                 2),
  ('stationery',         'Stationery',          'القرطاسية',          'قرتاسیە',            'قرتاسیە',             3),
  ('furniture',          'Furniture',           'الأثاث',             'کەلوپەل',            'کەلوپەل',             4),
  ('household_appliances','Household appliances','الأجهزة المنزلية',  'ئامێرەکانی ماڵ',     'ئامێرێن مالێ',        5),
  ('other',              'Other in-kind items', 'مواد عينية أخرى',    'شتومەکی عەینی تر',   'تشتێن عەینی یێن دی',  6)
ON CONFLICT (slug) DO NOTHING;

-- 3. Dashboard switches for the donate screen.
--    donation_projects_visible — "The project list can also be hidden, leaving
--      only the General Donation option. Showing and hiding projects must be
--      controlled from the Dashboard."
--    donation_comprehensive_enabled — "Fifth: Comprehensive Grantor Option",
--      the Grant Now / Comprehensive Grant general-fund choice.
INSERT INTO app_settings (key, value) VALUES
  ('donation_projects_visible', '1'),
  ('donation_comprehensive_enabled', '1')
ON CONFLICT (key) DO NOTHING;
