-- 086 — "Eighth: Sponsorship Schedule and Calendar".
--
-- Already present, reused: sponsorships.schedule_interval
-- (weekly|monthly|quarterly|yearly) and sponsorships.next_due_date give each
-- sponsorship its recurrence rule and its next date. What was missing is the
-- schedule itself — a row per due date — which is what upcoming / due /
-- overdue / history tracking and the reminders need.

-- 1. Admin-managed assistance types ("4. Scalability": new types of assistance
--    without programming changes). sponsorships.sponsorship_type is a free
--    VARCHAR, so this is a curated picker over the same values rather than a
--    constraint — existing rows keep working untouched.
CREATE TABLE IF NOT EXISTS sponsorship_types (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  -- Default recurrence suggested when staff pick this type.
  default_interval VARCHAR(16) NOT NULL DEFAULT 'monthly'
                    CHECK (default_interval IN ('weekly','monthly','quarterly','yearly')),
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sponsorship_types (slug, name_en, name_ar, name_ckb, name_kmr, default_interval, display_order) VALUES
  ('orphan_monthly', 'Monthly orphan assistance', 'مساعدة شهرية للأيتام', 'یارمەتی مانگانەی هەتیوان', 'هاریکاریا مەهانە یا سێویان', 'monthly', 1),
  ('widow_support',  'Widow assistance',          'مساعدة الأرامل',       'یارمەتی بێوەژنان',        'هاریکاریا بیوەژنان',        'monthly', 2),
  ('house_rent',     'House-rent payment',        'دفع إيجار المنزل',     'پارەی کرێی خانوو',        'پارێ کریا خانی',            'monthly', 3),
  ('other',          'Other recurring assistance','مساعدة متكررة أخرى',   'یارمەتی دووبارەی تر',     'هاریکاریا دووبارە یا دی',   'monthly', 4)
ON CONFLICT (slug) DO NOTHING;

-- 2. The schedule itself: one row per due date per sponsorship. Generated from
--    the sponsorship's interval, so "the system should automatically create a
--    schedule for each case" is a data operation, not manual entry.
--
--    status drives the tracking screen:
--      upcoming — due in the future
--      due      — due today / within the grace window, not yet paid
--      overdue  — past due, not paid
--      paid     — settled (history)
--      skipped  — deliberately passed over by staff (history)
CREATE TABLE IF NOT EXISTS sponsorship_schedule (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sponsorship_id  BIGINT      NOT NULL REFERENCES sponsorships(id) ON DELETE CASCADE,
  due_date        DATE        NOT NULL,
  amount          NUMERIC(14,2) NOT NULL DEFAULT 0.00,
  currency        CHAR(3)     NOT NULL DEFAULT 'IQD',
  status          VARCHAR(16) NOT NULL DEFAULT 'upcoming'
                   CHECK (status IN ('upcoming','due','overdue','paid','skipped')),
  paid_at         TIMESTAMP,
  notes           TEXT,
  -- Reminder bookkeeping so a notification is never sent twice for the same
  -- occurrence, per recipient side.
  reminded_grantor_at   TIMESTAMP,
  reminded_recipient_at TIMESTAMP,
  created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (sponsorship_id, due_date)
);

CREATE INDEX IF NOT EXISTS idx_sponsorship_schedule_sponsorship
  ON sponsorship_schedule(sponsorship_id);
CREATE INDEX IF NOT EXISTS idx_sponsorship_schedule_due
  ON sponsorship_schedule(due_date, status);

CREATE TRIGGER trg_sponsorship_schedule_updated_at
  BEFORE UPDATE ON sponsorship_schedule
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. Reminder lead time, editable from the Dashboard (no redeploy).
INSERT INTO app_settings (key, value) VALUES
  ('sponsorship_reminder_days_before', '3')
ON CONFLICT (key) DO NOTHING;
