-- 093 — Staff approval for a user's own name / photo change.
--
-- Until now profile.Set wrote full_name and profile_picture straight to
-- user_profiles. The client wants both to be reviewed first: the user submits,
-- an admin approves or rejects, and only an approval touches the profile.
--
-- One row per pending change, holding the proposed value. The live profile is
-- NOT modified until approval, so a rejected request simply disappears and the
-- displayed profile never flickered to the unapproved value.
CREATE TABLE IF NOT EXISTS profile_change_requests (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- 'full_name' | 'profile_picture'. Free text rather than an enum so another
  -- reviewable field is a new value, not a migration.
  field       VARCHAR(32) NOT NULL,
  -- What the profile held when the request was raised, so a reviewer can see
  -- the change rather than just the proposal.
  old_value   TEXT        NOT NULL DEFAULT '',
  new_value   TEXT        NOT NULL DEFAULT '',
  status      VARCHAR(16) NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','approved','rejected')),
  created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at  TIMESTAMP,
  decided_by  INTEGER     REFERENCES users(id) ON DELETE SET NULL,
  -- Optional note from the reviewer when rejecting.
  decide_note TEXT        NOT NULL DEFAULT ''
);

-- The admin queue is "pending, oldest first"; the app asks "does this user
-- have anything pending?" — both covered here.
CREATE INDEX IF NOT EXISTS idx_profile_change_requests_status
  ON profile_change_requests (status, created_at);
CREATE INDEX IF NOT EXISTS idx_profile_change_requests_user
  ON profile_change_requests (user_id, status);

-- Only one pending request per (user, field): re-submitting replaces the
-- proposal rather than stacking a queue of them behind one reviewer.
CREATE UNIQUE INDEX IF NOT EXISTS uq_profile_change_pending
  ON profile_change_requests (user_id, field)
  WHERE status = 'pending';
