-- 101 — City Guide sub-categories: the second half of "Main and subcategory".
--
-- The six sectors are curated (city_sectors, completed in migration 100), but
-- the sub-category was city_directory_entries.category — a free-text column
-- whose live values include 'training', 'cooperative', 'asdsa', 'ب' and 'ر'.
-- That cannot satisfy a required field called "Main and subcategory", and it
-- cannot drive a filter: two people typing "Pharmacy" and "pharmacies" produce
-- two different categories.
--
-- This adds the curated list the spec spells out under each sector. The free
-- text column is deliberately left in place and untouched — existing entries
-- keep working and keep displaying, and staff can retag them from the Admin
-- Panel at their own pace rather than losing data to a migration.
CREATE TABLE IF NOT EXISTS city_categories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  -- Which of the six sectors this sub-category belongs under. Free text rather
  -- than an FK so retiring a sector never cascades away its sub-categories.
  sector_slug   VARCHAR(64)  NOT NULL,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- The app asks for "the sub-categories of this sector, in order".
CREATE INDEX IF NOT EXISTS idx_city_categories_sector
  ON city_categories (sector_slug, display_order);

INSERT INTO city_categories (slug, sector_slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  -- 1. Security and Sovereign Services
  ('police_stations',    'government', 'Police stations',                  'مراكز الشرطة',              'بنکەکانی پۆلیس',            'بنکێن پۆلیسان',             1),
  ('civil_defense',      'government', 'Civil defense / fire stations',    'الدفاع المدني والإطفاء',    'بەرگری شارستانی و ئاگرکوژێنەوە', 'بەرگریا شارستانی و ئاگرڤەمراندن', 2),
  ('ambulance',          'government', 'Emergency ambulance centers',      'مراكز الإسعاف الطارئ',      'ناوەندەکانی فریاکەوتن',     'ناڤەندێن هاریکاریا لەزگین', 3),
  ('courts',             'government', 'Judicial departments and courts',  'الدوائر القضائية والمحاكم', 'بەشە دادوەرییەکان و دادگاکان', 'بەشێن دادوەری و دادگەه',  4),
  ('civil_status',       'government', 'Civil status, passport and ID',    'الأحوال المدنية والجوازات والبطاقة الوطنية', 'باری شارستانی، پاسپۆرت و کارتی نیشتمانی', 'بارێ شارستانی، پاسپۆرت و کارتا نیشتمانی', 5),
  -- 2. Health and Medical Services
  ('hospitals',          'health',     'Hospitals (public / private)',     'المستشفيات (حكومي/أهلي)',   'نەخۆشخانەکان (گشتی/تایبەت)', 'نەخۆشخانە (گشتی/تایبەت)',  10),
  ('phc_centers',        'health',     'Primary healthcare centers',       'مراكز الرعاية الصحية الأولية', 'ناوەندەکانی چاودێری تەندروستی سەرەتایی', 'ناڤەندێن چاڤدێریا تەندروستی یا سەرەتایی', 11),
  ('clinics',            'health',     'Specialized clinics and complexes','العيادات والمجمعات الطبية', 'کلینیکە پسپۆڕەکان و کۆمەڵگا پزیشکییەکان', 'کلینیکێن پسپۆر و کۆمەلگەهێن پزیشکی', 12),
  ('pharmacies',         'health',     'Pharmacies and medical supplies',  'الصيدليات ومخازن المستلزمات الطبية', 'دەرمانخانەکان و کۆگای پێداویستی پزیشکی', 'دەرمانخانە و کۆگەهێن پێدڤیێن پزیشکی', 13),
  ('labs_radiology',     'health',     'Laboratories and radiology',       'المختبرات ومراكز الأشعة',   'تاقیگەکان و ناوەندەکانی تیشک', 'تاقیگەه و ناڤەندێن تیشکێ',  14),
  -- 3. Commerce and Business
  ('malls',              'commercial', 'Malls and shopping complexes',     'المولات والمجمعات التجارية','مۆڵ و کۆمەڵگا بازرگانییەکان', 'مۆل و کۆمەلگەهێن بازرگانی', 20),
  ('retail_shops',       'commercial', 'Retail shops',                     'المحال التجارية',           'دوکانە بازرگانییەکان',      'دوکانێن بازرگانی',          21),
  ('barbers_beauty',     'commercial', 'Barbershops and beauty centers',   'الحلاقة ومراكز التجميل',    'ئارایشتگا و ناوەندەکانی جوانکاری', 'ئارایشتگەه و ناڤەندێن جوانکاریێ', 22),
  ('professional_offices','commercial','Real-estate, legal and engineering offices','المكاتب العقارية والقانونية والهندسية','نووسینگە خانووبەرە، یاسایی و ئەندازیارییەکان','نڤیسینگەهێن خانی، یاسایی و ئەندازیاری', 23),
  ('exchange_transfer',  'commercial', 'Currency exchange and transfers',  'الصرافة وشركات التحويل',    'گۆڕینەوەی دراو و کۆمپانیاکانی گواستنەوە', 'گوهۆرینا دراڤی و کومپانیایێن گوهاستنێ', 24),
  -- 4. Industry and Production
  ('factories',          'industrial', 'Plants and factories',             'المعامل والمصانع',          'کارگە و فابریکەکان',        'کارگەه و فابریقە',          30),
  ('workshops',          'industrial', 'Workshops (auto, smithing, carpentry)','الورش (تصليح السيارات، حدادة، نجارة)','وۆرکشۆپەکان (ئۆتۆمبێل، ئاسنگەری، دارتاشی)','وۆرکشۆپ (ئۆتۆمبێل، ئاسنگەری، دارتاشی)', 31),
  ('warehouses',         'industrial', 'Depots and warehouses',            'المخازن والمستودعات',       'کۆگا و ئەمبارەکان',         'کۆگەه و ئەمبار',            32),
  -- 5. Tourism, Heritage and Entertainment
  ('heritage_sites',     'tourism',    'Archaeological and heritage sites','المواقع الأثرية والتراثية',  'شوێنە شوێنەوارییەکان و کەلەپووری', 'جهێن شوێنەواری و کەلەپووری', 40),
  ('religious_sites',    'tourism',    'Religious sites',                  'المواقع الدينية',           'شوێنە ئایینییەکان',         'جهێن ئایینی',               41),
  ('hotels',             'tourism',    'Hotels and guesthouses',           'الفنادق ودور الضيافة',      'هۆتێل و میوانخانەکان',      'هۆتێل و میڤانخانە',         42),
  ('restaurants_cafes',  'tourism',    'Restaurants and cafés',            'المطاعم والمقاهي',          'چێشتخانە و قاوەخانەکان',    'خوارنگەه و قاوەخانە',       43),
  ('parks_sports',       'tourism',    'Parks, amusement and sports clubs','المتنزهات والملاهي والأندية الرياضية','پارک، شوێنی خۆشی و یانەی وەرزشی', 'پارک، جهێن خۆشیێ و یانێن وەرزشی', 44),
  -- 6. Education and Public Services
  ('universities',       'education',  'Universities and colleges',        'الجامعات والكليات',         'زانکۆ و کۆلێژەکان',         'زانکۆ و کۆلێژ',             50),
  ('schools',            'education',  'Schools and kindergartens',        'المدارس ورياض الأطفال',     'قوتابخانە و باخچەی ساوایان', 'خواندنگەه و باخچەیێن زاڕۆکان', 51),
  ('institutes',         'education',  'Training and vocational institutes','المعاهد التدريبية والمهنية','پەیمانگا ڕاهێنان و پیشەییەکان', 'پەیمانگەهێن راهێنان و پیشەیی', 52),
  ('public_services',    'education',  'Public service departments',       'دوائر الخدمات العامة',      'بەشەکانی خزمەتگوزاری گشتی', 'بەشێن خزمەتێن گشتی',        53)
ON CONFLICT (slug) DO NOTHING;
