-- 103 — M7: donation TYPES become dashboard-managed rows instead of Go code.
--
-- THE GAP THIS CLOSES
-- The client asked for "التحكم الكامل بجميع الخيارات من لوحة الإدارة دون
-- الحاجة إلى تحديث برمجي" over four things: donation types, projects,
-- edit/delete projects, and payment methods. Three already work as rows —
-- project_categories (029), payment_methods (084), inkind_categories (085) —
-- each with add/edit/reorder/delete. The donor-facing giving TYPE did not:
-- it was a hardcoded switch in Go (internal/donations/donations.go
-- normalizeDonationType) plus a hardcoded allowlist in
-- internal/handlers/admin_create.go, so a fourth type needed a code change and
-- a redeploy. This table is the missing row store.
--
-- SCOPE — donation_type, NOT donation_kind. THESE ARE DIFFERENT COLUMNS.
--   donations.donation_type (migration 028) is the donor's giving type —
--     general / zakat / sadaqah. Plain VARCHAR(20), NO check constraint, so it
--     can take new values additively. That is what this migration extends.
--   donations.donation_kind (001_full_v2.sql:390) is INTERNAL ROUTING and
--     carries CHECK (donation_kind IN ('general','campaign','sponsorship',
--     'in_kind','operational')). Extending THAT would mean dropping and
--     recreating a live CHECK constraint — a destructive change — and each
--     kind also has a whole flow behind it (a campaign id, a sponsorship
--     record, the in-kind form), so a new kind would be a row with no
--     behaviour. Deliberately NOT touched here; it is an owner decision.
--
-- Shape is copied verbatim from inkind_categories (085) so the existing admin
-- CMS pattern — slug + 4 language names + display_order + active — and the
-- Trash/restore path (H15) carry over with no new conventions.
CREATE TABLE IF NOT EXISTS donation_types (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  -- Mirrors inkind_categories.created_by: a plain INTEGER audit stamp, not a
  -- declared FK (the sibling CMS tables do not constrain it either), so there
  -- is no foreign key here needing an index.
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index justification — there are exactly two query shapes against this table:
--
--   1. The list reads, admin and public:
--        SELECT ... FROM donation_types [WHERE active = 1] ORDER BY display_order, id
--      `active` is the WHERE column and (display_order, id) is the ORDER BY, so
--      one composite index serves the filter and removes the sort for the
--      public/app path, which is the hot one (every donate screen open).
CREATE INDEX IF NOT EXISTS idx_donation_types_active_order
  ON donation_types (active, display_order, id);
--
--   2. The per-donation validation lookup:
--        SELECT 1 FROM donation_types WHERE slug = $1 AND active = 1
--      already served by the UNIQUE constraint on slug — no second index, an
--      extra one would only cost writes.

-- Seed the three types that were hardcoded, so behaviour is identical the
-- moment this lands and no existing donation row becomes unlabelled.
-- Every translation below is copied from strings ALREADY SHIPPED in the app and
-- dashboard locale files (app_translations.dart 'Zakat'/'Sadaqah' per language;
-- admin-web locales status.general/zakat/sadaqah) — no new Kurdish was written
-- for this migration.
INSERT INTO donation_types (slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('general',  'General',  'عام',  'گشتی',   'گشتی',   1),
  ('zakat',    'Zakat',    'زكاة', 'زەکات',  'زەکات',  2),
  ('sadaqah',  'Sadaqah',  'صدقة', 'سەدەقە', 'سەدەقە', 3)
ON CONFLICT (slug) DO NOTHING;

-- ─── DOWN (reversal) ───────────────────────────────────────────────────────
-- This repo's runner (internal/db/migrate.go) is forward-only and records each
-- file in schema_migrations; there is no .down.sql convention to follow, so the
-- reversal is recorded here and was EXECUTED against a local database before
-- this migration was committed. It is a clean reversal because 103 only ADDS:
-- it creates one new table and writes only into that table, so dropping the
-- table restores the exact prior schema and loses no pre-existing data.
--
--   DROP INDEX IF EXISTS idx_donation_types_active_order;
--   DROP TABLE IF EXISTS donation_types;
--   DELETE FROM schema_migrations WHERE version = '103_donation_types.sql';
--
-- Note for whoever runs it later: donation rows keep their donation_type text
-- either way — donations.donation_type is a VARCHAR on the donations table and
-- is never touched by this migration. After a reversal the Go fallback list
-- (general/zakat/sadaqah) takes over again, so any admin-added type would stop
-- being accepted on NEW donations while old rows keep their stored value.
