-- 114 — H20: a change to the main-admin account must be confirmed on BOTH
-- channels, phone AND email.
--
-- THE GAP THIS CLOSES
-- The users resource already answers "MAY this caller write to this row?"
-- (internal/handlers/admin_user_guard.go — the H13 tier floor plus the rule
-- that a staff sign-in number is the Super-Admin's to move). What it has never
-- answered is "does the PERSON WHOSE ACCOUNT THIS IS know it is happening?"
-- Authorisation is not confirmation: three super_admin accounts exist in
-- production and each may write to the others, so any one of them — or anyone
-- holding one of their live sessions — could rewrite a peer's sign-in number,
-- set a password on it, or move its tier, in one request, silently.
--
-- The client's answer is a confirmation code delivered out of band, and
-- deliberately on TWO channels at once: "التغيير فقط عبر رمز تأكيد يُرسل عبر
-- الهاتف والبريد الإلكتروني معاً". Two channels because one is exactly what an
-- attacker who has already taken a phone number holds.
--
-- WHY A TABLE AND NOT otp_codes
-- otp_codes is keyed BY PHONE, one row per number, upserted on every send. It
-- can express "this number has a pending code" and nothing else. A confirmation
-- here has to remember four more things: whose account is being changed, who is
-- changing it, WHICH KIND of change was authorised, and — the part that made
-- the decision — WHICH CHANNELS ACTUALLY DELIVERED. None of that fits a keyed-
-- by-phone upsert, and grafting it on would break the login OTP that already
-- lives there: a confirmation sent to a super_admin's phone would silently
-- overwrite the sign-in code they were mid-way through typing.
--
-- The primitives are still shared, not re-invented: the code is generated by
-- auth.GenerateCode, hashed with bcrypt, capped at auth.OTPMaxAttempts guesses
-- and expired on auth.OTPTTL, exactly like every other code in this system.
--
-- WHY BOTH TIMESTAMPS ARE RECORDED
-- A row is written ONLY after both sends have been accepted, so the presence of
-- a row is itself the proof that two channels were used, and the two timestamps
-- say when. A half-delivered confirmation is never stored: if email delivery is
-- unavailable the change is refused before anything is sent, and the refusal —
-- not a row — is what the operator sees. See the file header of
-- internal/handlers/admin_main_admin_guard.go for that decision and its
-- reasoning.
--
-- WHAT IS DELIBERATELY NOT STORED
-- The new value being confirmed. Binding a challenge to the exact new phone
-- number or password would be marginally tighter, but for the password case it
-- would mean writing a digest of a credential into a second table — the class
-- of mistake this repo has already had to remove once. change_kind is the
-- binding instead: a code issued to move a tier cannot be spent to rewrite a
-- phone, and within one kind the actor was already authorised for that kind of
-- change by the H13 guard.
--
-- ADDITIVE ONLY: one new table and one new index. No existing column is added
-- to, dropped, retyped or backfilled, and no existing row is touched. With this
-- migration applied and the Go code reverted, nothing reads or writes the table
-- and the system behaves exactly as before.

CREATE TABLE IF NOT EXISTS admin_change_confirmations (
  id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Whose account is being changed. The code goes to THIS person's phone and
  -- email, which is what makes it a protection of the account rather than a
  -- second hoop for whoever is already holding a session.
  target_user_id INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Who asked for the change. A challenge is spendable only by the actor who
  -- raised it, so one Super-Admin cannot ride another's pending confirmation.
  actor_user_id  INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- phone | email | password | staff_tier — see mainAdminChangeKinds in Go.
  change_kind    VARCHAR(32) NOT NULL,
  -- bcrypt of the 6-digit code. Never the code itself, and never returned by
  -- any endpoint.
  code_hash      TEXT        NOT NULL,
  attempts       INTEGER     NOT NULL DEFAULT 0,
  -- When each channel accepted the message. Both are set on insert today; they
  -- are nullable so a future partial-delivery policy can be recorded without a
  -- destructive migration.
  phone_sent_at  TIMESTAMP,
  email_sent_at  TIMESTAMP,
  created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at     TIMESTAMP   NOT NULL,
  -- Set when the code is spent, or when the challenge is voided (too many
  -- guesses). Either way the row stops being usable and stays as evidence.
  consumed_at    TIMESTAMP
);

-- The only read path: "is there a live challenge for this target, of this kind,
-- raised by this actor?" Partial on consumed_at IS NULL because spent and
-- voided rows are audit history and are never looked up again.
CREATE INDEX IF NOT EXISTS idx_admin_change_conf_live
  ON admin_change_confirmations (target_user_id, change_kind, actor_user_id)
  WHERE consumed_at IS NULL;

-- ─── DOWN (reversal) ───────────────────────────────────────────────────────
-- This repo's runner (internal/db/migrate.go) is forward-only and records each
-- file in schema_migrations; there is no .down.sql convention, so the reversal
-- is recorded here and WAS EXECUTED against a local database (UP → DOWN → UP)
-- before this migration was committed:
--
--   DROP INDEX IF EXISTS idx_admin_change_conf_live;
--   DROP TABLE IF EXISTS admin_change_confirmations;
--   DELETE FROM schema_migrations WHERE version = '114_main_admin_change_confirmations.sql';
--
-- Reversing loses only pending and spent confirmation records — no user, no
-- permission and no account state lives here. Every other table is untouched.
