-- 120_chat_groups.sql
-- OPOS #25284 — staff-created group chats. Two modes on one schema:
-- kind='masked' (donor/beneficiary/volunteer, identities hidden behind a
-- staff-assigned label) and kind='team' (volunteer team coordination, real
-- names). See docs/superpowers/specs/2026-09-12-masked-group-chats-design.md
-- for the full design and why one schema serves both modes.
--
-- No foreign-key constraints, matching this codebase's convention — the
-- Store validates existence explicitly.

CREATE TABLE IF NOT EXISTS chat_group_threads (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind                  VARCHAR(16) NOT NULL CHECK (kind IN ('masked', 'team')),
  -- Shown to members. Team groups only — for a masked group this is always
  -- '', enforced in the Store (never let staff type an identifying title
  -- like "Ahmed <-> donor Zaid" onto a masked group).
  member_title          VARCHAR(200) NOT NULL DEFAULT '',
  created_by_staff_id   INTEGER NOT NULL,
  -- chatlifecycle's real vocabulary (open|paused|ended) — NOT a bespoke
  -- active/archived enum. Registered with chatlifecycle in a later phase;
  -- the columns exist now so the schema never needs a second migration for
  -- what lifecycle actually requires.
  lifecycle             VARCHAR(16) NOT NULL DEFAULT 'open',
  lifecycle_reason      TEXT NOT NULL DEFAULT '',
  lifecycle_changed_at  TIMESTAMP,
  lifecycle_changed_by  INTEGER,
  archived_at           TIMESTAMP,
  archived_by           INTEGER,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Staff-only context ("Case #123 coordination"). A SEPARATE table, not a
-- column on chat_group_threads, so a member-facing list query can never
-- reach it even by a future SELECT * mistake.
CREATE TABLE IF NOT EXISTS chat_group_staff_notes (
  group_id              BIGINT PRIMARY KEY,
  context_note          TEXT NOT NULL DEFAULT '',
  created_by            INTEGER NOT NULL,
  updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_group_members (
  -- The client-facing speaker handle for masked groups — NEVER user_id.
  -- Scoped to one (group, user) pair, so it identifies a speaker within a
  -- group without correlating that person across groups.
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id              BIGINT NOT NULL,
  user_id               INTEGER NOT NULL,
  role_in_group         VARCHAR(16) NOT NULL DEFAULT '', -- donor|beneficiary|volunteer|staff, informational
  -- ALWAYS derived server-side from the parent group's kind at insert time
  -- (see internal/chatgroups.insertMembers) — never accepted as caller
  -- input, so a masked group cannot end up with an unmasked member.
  masked                BOOLEAN NOT NULL DEFAULT true,
  masked_label          VARCHAR(100),
  added_by_staff_id     INTEGER NOT NULL,
  added_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Soft-remove ONLY, never DELETE — a deleted row breaks historical label
  -- resolution for that member's past messages and fails open.
  removed_at            TIMESTAMP,
  removed_by            INTEGER,
  CHECK (NOT masked OR (masked_label IS NOT NULL AND masked_label <> '')),
  UNIQUE (group_id, user_id)
);

-- Two active masked members in the same group can't collide on a label.
CREATE UNIQUE INDEX IF NOT EXISTS uq_chat_group_members_active_label
  ON chat_group_members (group_id, lower(masked_label))
  WHERE masked AND removed_at IS NULL;

CREATE TABLE IF NOT EXISTS chat_group_messages (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id              BIGINT NOT NULL,
  -- ALWAYS the real id. Masking is a read-time projection (see
  -- Store.ListMessagesForMember), never a storage-time decision.
  sender_user_id        INTEGER NOT NULL,
  body                  TEXT NOT NULL,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_group_messages_group
  ON chat_group_messages (group_id, id);

CREATE TABLE IF NOT EXISTS chat_group_reads (
  group_id              BIGINT NOT NULL,
  user_id               INTEGER NOT NULL,
  last_read_msg_id      BIGINT NOT NULL DEFAULT 0,
  UNIQUE (group_id, user_id)
);

-- Mirrors chat_contact_blocks. Wired up in a later phase (the K19 filter
-- must gate on group.kind = 'masked', not the existing staff-exemption
-- logic, which would silently disable it since staff is always present in
-- a masked group) — table created now so that phase needs no migration.
CREATE TABLE IF NOT EXISTS chat_group_contact_blocks (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id              BIGINT NOT NULL,
  message_id            BIGINT NOT NULL,
  blocked_user_id       INTEGER NOT NULL,
  reason                VARCHAR(64) NOT NULL DEFAULT '',
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_group_connect_requests (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_user_id     INTEGER NOT NULL,
  context_type          VARCHAR(16) NOT NULL CHECK (context_type IN ('donation', 'case')),
  context_id            BIGINT NOT NULL,
  -- Nullable: populated when the app already knows the specific counterpart
  -- (e.g. a sponsorship-derived beneficiary) — a bare donation id does not
  -- always determine one.
  target_hint           BIGINT,
  message               TEXT NOT NULL,
  -- Set when approved. Approval creates the group in the SAME transaction
  -- as this update (Store.ApproveConnectRequest) — there is never an
  -- "approved, no group yet" dangling state.
  group_id              BIGINT,
  status                VARCHAR(16) NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'approved', 'declined')),
  decline_reason        TEXT NOT NULL DEFAULT '',
  decided_by_staff_id   INTEGER,
  decided_at            TIMESTAMP,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- A resubmit while one is already pending is an idempotent no-op, not a
-- second row for staff to triage.
CREATE UNIQUE INDEX IF NOT EXISTS uq_chat_group_connect_requests_pending
  ON chat_group_connect_requests (requester_user_id, context_type, context_id)
  WHERE status = 'pending';
