-- 120 — Districts/neighborhoods CMS (OPOS #25271).
--
-- The registration form's Nineveh-specific "District" and "Neighborhood"
-- pickers (humanitarian/lib/data/nineveh_districts.dart /
-- nineveh_neighborhoods.dart) were a hardcoded, English-only Dart const list
-- with no admin path to add a missing one. Mirrors the city_categories CMS
-- pattern (migration 101): name_en/ar/ckb/kmr + display_order + active,
-- scoped by group_key instead of sector_slug.
--
-- group_key values:
--   nineveh_district            -- the 10 Nineveh governorate districts
--   nineveh_neighborhood_left   -- Mosul left-bank (east) neighborhoods
--   nineveh_neighborhood_right  -- Mosul right-bank (west) neighborhoods
--
-- KURDISH TRANSLATION NOTE: name_ckb/name_kmr are filled in for the 10
-- governorate-level districts (Mosul, Sinjar, Tel Afar, etc.) -- these are
-- major, widely-documented places with well-established Kurdish names. They
-- are deliberately left BLANK for the 24 Mosul-city neighborhoods: this
-- project's own rule is "Kurdish must not be invented" (app_translations.dart),
-- and neighbourhood-level place names are exactly the kind of fact that must
-- not be guessed at. A blank falls back to Arabic/English automatically
-- (localizedContentFromValues) rather than showing a wrong Kurdish name.
-- An admin who has the correct names can fill them in from the dashboard --
-- that CMS access is the other half of this migration.
CREATE TABLE IF NOT EXISTS districts (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key     VARCHAR(32)  NOT NULL,
  slug          VARCHAR(64)  NOT NULL,
  name_en       VARCHAR(120) NOT NULL,
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (group_key, slug)
);

CREATE INDEX IF NOT EXISTS idx_districts_group_order
  ON districts (group_key, display_order);

INSERT INTO districts (group_key, slug, name_en, name_ar, name_ckb, name_kmr, display_order) VALUES
  ('nineveh_district', 'mosul',        'Mosul',        'الموصل',      'مووسل',        'مووسل',        1),
  ('nineveh_district', 'tel_afar',     'Tel Afar',     'تلعفر',       'تەلعەفەر',     'تەلعەفەر',     2),
  ('nineveh_district', 'sinjar',       'Sinjar',       'سنجار',       'شنگال',        'شەنگال',       3),
  ('nineveh_district', 'tel_kaif',     'Tel Kaif',     'تلكيف',       'تەلکێف',       'تەلکێف',       4),
  ('nineveh_district', 'al_hamdaniya', 'Al-Hamdaniya', 'الحمدانية',   'حەمدانیە',     'حەمدانیە',     5),
  ('nineveh_district', 'al_shikhan',   'Al-Shikhan',   'الشيخان',     'شێخان',        'شێخان',        6),
  ('nineveh_district', 'al_baaj',      'Al-Baaj',      'البعاج',      'بەعاج',        'بەعاج',        7),
  ('nineveh_district', 'hatra',        'Hatra',        'الحضر',       'هەتره',        'هەترا',        8),
  ('nineveh_district', 'makhmour',     'Makhmour',     'مخمور',       'مەخموور',      'مەخموور',      9),
  ('nineveh_district', 'al_qayyarah',  'Al-Qayyarah',  'القيارة',     'قەیارە',       'قەیارە',       10)
ON CONFLICT (group_key, slug) DO NOTHING;

INSERT INTO districts (group_key, slug, name_en, name_ar, display_order) VALUES
  ('nineveh_neighborhood_right', 'al_zanjili',          'Al-Zanjili',           'الزنجيلي',            1),
  ('nineveh_neighborhood_right', 'al_dawasa',            'Al-Dawasa',            'الدواسة',             2),
  ('nineveh_neighborhood_right', 'wadi_hajar',           'Wadi Hajar',           'وادي حجر',            3),
  ('nineveh_neighborhood_right', 'al_tanak',             'Al-Tanak',             'التنك',               4),
  ('nineveh_neighborhood_right', 'al_jadida',            'Al-Jadida',            'الجديدة',             5),
  ('nineveh_neighborhood_right', 'al_muthanna',          'Al-Muthanna',          'المثنى',              6),
  ('nineveh_neighborhood_right', 'al_nabi_yunus',        'Al-Nabi Yunus',        'النبي يونس',          7),
  ('nineveh_neighborhood_right', 'al_maidan',            'Al-Maidan',            'الميدان',             8),
  ('nineveh_neighborhood_right', 'bab_sinjar',           'Bab Sinjar',           'باب سنجار',           9),
  ('nineveh_neighborhood_right', '17_tammuz',            '17 Tammuz',            '17 تموز',             10),
  ('nineveh_neighborhood_right', 'al_mansour',           'Al-Mansour',           'المنصور',             11),
  ('nineveh_neighborhood_right', 'al_islah_al_zirai',    'Al-Islah al-Zira''i',  'الإصلاح الزراعي',     12)
ON CONFLICT (group_key, slug) DO NOTHING;

INSERT INTO districts (group_key, slug, name_en, name_ar, display_order) VALUES
  ('nineveh_neighborhood_left', 'al_karama',      'Al-Karama',      'الكرامة',       1),
  ('nineveh_neighborhood_left', 'al_zuhour',      'Al-Zuhour',      'الزهور',        2),
  ('nineveh_neighborhood_left', 'al_wahda',       'Al-Wahda',       'الوحدة',        3),
  ('nineveh_neighborhood_left', 'al_intisar',     'Al-Intisar',     'الانتصار',      4),
  ('nineveh_neighborhood_left', 'al_sukkar',      'Al-Sukkar',      'السكر',         5),
  ('nineveh_neighborhood_left', 'al_quds',        'Al-Quds',        'القدس',         6),
  ('nineveh_neighborhood_left', 'al_shurta',      'Al-Shurta',      'الشرطة',        7),
  ('nineveh_neighborhood_left', 'al_somer',       'Al-Somer',       'الصومر',        8),
  ('nineveh_neighborhood_left', 'al_noor',        'Al-Noor',        'النور',         9),
  ('nineveh_neighborhood_left', 'al_arabi',       'Al-Arabi',       'العربي',        10),
  ('nineveh_neighborhood_left', 'al_muhandiseen', 'Al-Muhandiseen', 'المهندسين',     11),
  ('nineveh_neighborhood_left', 'hay_al_tayaran', 'Hay al-Tayaran', 'حي الطيران',    12)
ON CONFLICT (group_key, slug) DO NOTHING;
