-- 121_chat_group_contact_blocks_fix.sql
-- Migration 120 created chat_group_contact_blocks with a shape that does not
-- fit this codebase's "refuse before storing" contact-info filter (see
-- internal/handlers/chat_contact_block.go): a blocked message is never
-- inserted into chat_group_messages, so a NOT NULL message_id could never be
-- populated. The table has no rows and no code references it yet (created in
-- Phase 1 purely as scaffolding "so a later phase needs no migration" — this
-- IS that later phase), so it is safe to drop and recreate with the shape
-- that actually matches chat_contact_blocks, the proven-correct precedent
-- this mirrors.
DROP TABLE IF EXISTS chat_group_contact_blocks;

CREATE TABLE IF NOT EXISTS chat_group_contact_blocks (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id       BIGINT    NOT NULL,
  -- Who tried. Never a staff member — the filter does not run on staff (see
  -- internal/handlers/chat_group_contact_block.go).
  sender_user_id INTEGER   NOT NULL,
  -- What was found: 'phone' | 'email' | 'both'. CHECKed in the database, same
  -- as chat_contact_blocks, so a future writer cannot invent a fourth value.
  kind           VARCHAR(8) NOT NULL CHECK (kind IN ('phone', 'email', 'both')),
  match_count    INTEGER   NOT NULL DEFAULT 1 CHECK (match_count > 0),
  redacted_body  TEXT      NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Mirrors idx_chat_contact_blocks_thread's rationale: staff open one group's
-- history ("what has been tried here?"). No sender-scoped index yet since no
-- query needs one (chat_contact_blocks' sender index exists because that
-- table also serves a cross-thread "this sender keeps trying" report that
-- chat groups has no equivalent of yet).
CREATE INDEX IF NOT EXISTS idx_chat_group_contact_blocks_group
  ON chat_group_contact_blocks (group_id, created_at DESC);
