-- 122_chat_group_audit_log.sql
-- "Who unmasked whom" — a standalone record of group-creation and
-- membership-change actions. Corrects an earlier design-spec assumption
-- that internal/staffactivity could be called directly for this: that
-- package is a read-only aggregator over other tables (permission_audit_log
-- etc.), with no generic write method. This table is deliberately NOT
-- wired into that aggregator's Load/Summary UNION query — surfacing these
-- entries in the Staff Activity dashboard page is a separate decision for
-- whichever phase builds the admin-web chat-groups UI, once it knows how
-- staff actually want this presented. No foreign keys, matching
-- chat_group_*'s existing convention (120_chat_groups.sql) — existence is
-- validated by the caller, not the database.
CREATE TABLE IF NOT EXISTS chat_group_audit_log (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id        BIGINT NOT NULL,
  -- 'created' | 'member_added' | 'member_removed'. CHECKed in the database
  -- so a future writer cannot invent a fourth value silently.
  action          VARCHAR(32) NOT NULL CHECK (action IN ('created', 'member_added', 'member_removed')),
  actor_staff_id  INTEGER NOT NULL,
  -- NULL for 'created' (no single target member); set for member_added/removed.
  target_user_id  INTEGER,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_group_audit_log_group
  ON chat_group_audit_log (group_id, created_at DESC);
