-- 128 — Like/comment/share on marriage-seeker profile cards (client note,
-- 2026-09-22, confirmed with the owner given the privacy angle on real
-- people's profiles: "Yes, add all three").
--
-- Mirrors migration 034's post_likes/post_comments exactly, scoped to
-- marriage_profiles instead of media_posts — same moderation shape (banned
-- words gate a comment to 'pending' for review, same as the News & Activities
-- feed), so one moderation queue design serves both. Not the generic
-- saved_items table Save already uses: likes and comments need a per-row
-- count and, for comments, per-row moderation state — saved_items carries
-- neither.
CREATE TABLE IF NOT EXISTS marriage_profile_likes (
  profile_id BIGINT    NOT NULL,
  user_id    INTEGER   NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_marriage_profile_likes_profile ON marriage_profile_likes (profile_id);

CREATE TABLE IF NOT EXISTS marriage_profile_comments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT      NOT NULL,
  user_id    INTEGER     NOT NULL,
  body       TEXT        NOT NULL,
  status     VARCHAR(16) NOT NULL DEFAULT 'approved'
             CHECK (status IN ('pending','approved','hidden')),
  flagged    SMALLINT    NOT NULL DEFAULT 0,
  created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_marriage_profile_comments_profile ON marriage_profile_comments (profile_id, status);
CREATE INDEX IF NOT EXISTS idx_marriage_profile_comments_status ON marriage_profile_comments (status);

ALTER TABLE marriage_profiles
  ADD COLUMN IF NOT EXISTS share_count INTEGER NOT NULL DEFAULT 0;
