-- 130 — Like/comment on donation campaigns (client report: campaign detail
-- screen was already showing "Likes"/"Comments" counts with nowhere to
-- generate one — campaigns.go's list query hardcoded both to 0).
--
-- Mirrors migration 128's marriage_profile_likes/marriage_profile_comments
-- exactly, scoped to campaigns instead — same moderation shape (banned words
-- gate a comment to 'pending' for review, one moderation queue design serves
-- media posts, marriage profiles, and now campaigns). Deliberately its own
-- pair of tables, not a shared post_id/item_type column bolted onto
-- post_likes/post_comments: those are keyed on bare post_id with no type
-- discriminator, so a campaign and a media post sharing the same numeric id
-- would silently merge their like/comment counts.
CREATE TABLE IF NOT EXISTS campaign_likes (
  campaign_id BIGINT    NOT NULL,
  user_id     INTEGER   NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (campaign_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_campaign_likes_campaign ON campaign_likes (campaign_id);

CREATE TABLE IF NOT EXISTS campaign_comments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT      NOT NULL,
  user_id     INTEGER     NOT NULL,
  body        TEXT        NOT NULL,
  status      VARCHAR(16) NOT NULL DEFAULT 'approved'
              CHECK (status IN ('pending','approved','hidden')),
  flagged     SMALLINT    NOT NULL DEFAULT 0,
  created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_campaign_comments_campaign ON campaign_comments (campaign_id, status);
CREATE INDEX IF NOT EXISTS idx_campaign_comments_status ON campaign_comments (status);
