-- 136 — Cities / districts (أقضية) / sub-districts (نواحي) per governorate,
-- managed from the dashboard (client meeting).
--
-- The 18 governorates stay a fixed list in the app (iraq_governorates.dart);
-- everything under them is staff-managed here, as a three-level tree:
--   city        — belongs to a governorate (parent_id NULL)
--   district    — قضاء, belongs to a city
--   subdistrict — ناحية, belongs to a district
-- `governorate` is the app's English key ('Nineveh', 'Baghdad', …) and is
-- repeated on every row so a whole governorate loads in one query.
--
-- District and sub-district are OPTIONAL in the app (owner decision): a
-- person can stop at the city. Their picks are stored as text on the profile
-- (area_district / area_subdistrict, below), like governorate/neighborhood —
-- a later rename or delete here never rewrites what someone registered with.
CREATE TABLE IF NOT EXISTS location_areas (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  governorate   VARCHAR(32)  NOT NULL,
  parent_id     INTEGER      REFERENCES location_areas(id) ON DELETE RESTRICT,
  level         VARCHAR(16)  NOT NULL CHECK (level IN ('city', 'district', 'subdistrict')),
  name_en       VARCHAR(120) NOT NULL DEFAULT '',
  name_ar       VARCHAR(120) NOT NULL DEFAULT '',
  name_ckb      VARCHAR(120) NOT NULL DEFAULT '',
  name_kmr      VARCHAR(120) NOT NULL DEFAULT '',
  display_order INTEGER      NOT NULL DEFAULT 0,
  active        SMALLINT     NOT NULL DEFAULT 1,
  created_by    INTEGER,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- A city hangs off the governorate itself; everything else needs a parent.
  CHECK ((level = 'city') = (parent_id IS NULL)),
  CHECK (name_ar <> '' OR name_en <> '')
);

CREATE INDEX IF NOT EXISTS idx_location_areas_gov ON location_areas (governorate, level, display_order);
CREATE INDEX IF NOT EXISTS idx_location_areas_parent ON location_areas (parent_id);
-- No two siblings with the same Arabic name (the stored, canonical name).
CREATE UNIQUE INDEX IF NOT EXISTS uq_location_areas_sibling_ar
  ON location_areas (governorate, COALESCE(parent_id, 0), level, name_ar)
  WHERE name_ar <> '';

-- Nineveh's ten districts (migration 120, the Nineveh-only picker) become
-- Nineveh's cities here, so nothing staff already maintain is lost.
INSERT INTO location_areas (governorate, level, name_en, name_ar, name_ckb, name_kmr, display_order, active)
SELECT 'Nineveh', 'city', d.name_en, d.name_ar, d.name_ckb, d.name_kmr, d.display_order, d.active
  FROM districts d
 WHERE d.group_key = 'nineveh_district'
   AND NOT EXISTS (
         SELECT 1 FROM location_areas a
          WHERE a.governorate = 'Nineveh' AND a.level = 'city' AND a.name_ar = d.name_ar
       );

-- The picked district / sub-district, as text (see above).
ALTER TABLE user_profiles
  ADD COLUMN IF NOT EXISTS area_district    TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS area_subdistrict TEXT NOT NULL DEFAULT '';
ALTER TABLE marriage_profiles
  ADD COLUMN IF NOT EXISTS area_district    TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS area_subdistrict TEXT NOT NULL DEFAULT '';
