-- PostgreSQL schema for humanitarian app
-- Hand-converted from humanitarianApp.sql (MySQL/phpMyAdmin dump)
-- Conventions:
--   bigint UNSIGNED  -> BIGINT
--   int UNSIGNED     -> INTEGER
--   tinyint(1)       -> SMALLINT (preserves 0/1 from MySQL inserts)
--   enum(...)        -> VARCHAR + CHECK constraint
--   AUTO_INCREMENT   -> GENERATED BY DEFAULT AS IDENTITY (sequences re-aligned in 003_sequences.sql)
--   ON UPDATE CURRENT_TIMESTAMP -> trigger applied to *_updated_at columns (see end of file)

SET client_encoding = 'UTF8';

-- ============================================================
-- Trigger function: keep updated_at fresh on row update
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- users  (created first; referenced by FKs further down)
-- ============================================================
CREATE TABLE users (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone       VARCHAR(255) NOT NULL UNIQUE,
  role_id     INTEGER,
  active      SMALLINT DEFAULT 1,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- app_notifications
-- ============================================================
CREATE TABLE app_notifications (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               INTEGER,
  role_id               INTEGER,
  title                 VARCHAR(255) NOT NULL,
  title_ar              VARCHAR(255),
  body                  TEXT NOT NULL,
  body_ar               TEXT,
  notification_type     VARCHAR(128),
  notification_category VARCHAR(32) NOT NULL DEFAULT 'normal',
  priority              INTEGER NOT NULL DEFAULT 0,
  action_url            VARCHAR(255),
  related_entity_type   VARCHAR(64),
  related_entity_id     BIGINT,
  is_read               SMALLINT NOT NULL DEFAULT 0,
  read_at               TIMESTAMP,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_app_notifications_user_read ON app_notifications(user_id, is_read);
CREATE INDEX idx_app_notifications_role ON app_notifications(role_id);
CREATE INDEX idx_app_notifications_priority ON app_notifications(is_read, notification_category, priority, created_at);

-- ============================================================
-- app_notification_devices
-- ============================================================
CREATE TABLE app_notification_devices (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL,
  role_id     INTEGER,
  fcm_token   VARCHAR(512) NOT NULL UNIQUE,
  platform    VARCHAR(32) NOT NULL DEFAULT 'android',
  is_active   SMALLINT NOT NULL DEFAULT 1,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_app_notification_devices_user ON app_notification_devices(user_id);
CREATE INDEX idx_app_notification_devices_role ON app_notification_devices(role_id);
CREATE INDEX idx_app_notification_devices_active ON app_notification_devices(is_active);

-- ============================================================
-- app_notification_reads
-- ============================================================
CREATE TABLE app_notification_reads (
  notification_id BIGINT NOT NULL,
  user_id         INTEGER NOT NULL,
  read_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (notification_id, user_id)
);
CREATE INDEX idx_app_notification_reads_user ON app_notification_reads(user_id);

-- ============================================================
-- api_access_tokens
-- ============================================================
CREATE TABLE api_access_tokens (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL,
  token_selector  CHAR(18) NOT NULL UNIQUE,
  token_hash      CHAR(64) NOT NULL,
  user_agent      VARCHAR(255),
  ip_address      VARCHAR(45),
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at    TIMESTAMP,
  expires_at      TIMESTAMP NOT NULL,
  revoked_at      TIMESTAMP
);
CREATE INDEX idx_api_access_tokens_user ON api_access_tokens(user_id);
CREATE INDEX idx_api_access_tokens_expires ON api_access_tokens(expires_at);

-- ============================================================
-- beneficiary_cases
-- ============================================================
CREATE TABLE beneficiary_cases (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               INTEGER,
  case_code             VARCHAR(64) NOT NULL UNIQUE,
  public_title          VARCHAR(255) NOT NULL,
  public_title_ar       VARCHAR(255),
  full_name             VARCHAR(255),
  national_id           VARCHAR(64),
  phone                 VARCHAR(64),
  city                  VARCHAR(128),
  district              VARCHAR(128),
  address               TEXT,
  family_members_count  INTEGER,
  income_amount         NUMERIC(14,2),
  housing_status        VARCHAR(128),
  work_status           VARCHAR(128),
  health_status         TEXT,
  education_status      TEXT,
  actual_needs          TEXT,
  priority_level        VARCHAR(16) NOT NULL DEFAULT 'medium'
                         CHECK (priority_level IN ('low','medium','high','urgent')),
  verification_status   VARCHAR(32) NOT NULL DEFAULT 'submitted'
                         CHECK (verification_status IN ('draft','submitted','under_review','needs_changes','approved','rejected','archived')),
  public_visibility     VARCHAR(16) NOT NULL DEFAULT 'code_only'
                         CHECK (public_visibility IN ('code_only','summary','hidden')),
  review_notes          TEXT,
  reviewed_by_user_id   INTEGER,
  reviewed_at           TIMESTAMP,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_beneficiary_cases_user ON beneficiary_cases(user_id);
CREATE INDEX idx_beneficiary_cases_status ON beneficiary_cases(verification_status);
CREATE INDEX idx_beneficiary_cases_city_priority ON beneficiary_cases(city, priority_level);

-- ============================================================
-- beneficiary_case_documents
-- ============================================================
CREATE TABLE beneficiary_case_documents (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id             BIGINT NOT NULL,
  document_type       VARCHAR(128) NOT NULL,
  file_path           VARCHAR(500) NOT NULL,
  public_allowed      SMALLINT NOT NULL DEFAULT 0,
  uploaded_by_user_id INTEGER,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_beneficiary_case_documents_case ON beneficiary_case_documents(case_id);
CREATE INDEX idx_beneficiary_case_documents_type ON beneficiary_case_documents(document_type);

-- ============================================================
-- beneficiary_project_requests
-- ============================================================
CREATE TABLE beneficiary_project_requests (
  id                                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                                INTEGER NOT NULL,
  project_title                          VARCHAR(255) NOT NULL,
  project_title_ar                       VARCHAR(255),
  category                               VARCHAR(128) NOT NULL,
  category_ar                            VARCHAR(128),
  summary                                TEXT NOT NULL,
  summary_ar                             TEXT,
  description_long                       TEXT NOT NULL,
  description_long_ar                    TEXT,
  amount_needed                          NUMERIC(14,2) NOT NULL,
  raised_amount                          INTEGER NOT NULL DEFAULT 0,
  currency                               CHAR(3) NOT NULL DEFAULT 'IQD',
  location                               VARCHAR(255) NOT NULL,
  location_ar                            VARCHAR(255),
  beneficiary_community_name             VARCHAR(255) NOT NULL,
  beneficiary_community_name_ar          VARCHAR(255),
  people_affected_total                  INTEGER,
  male_count                             INTEGER,
  female_count                           INTEGER,
  volunteer_age_profile                  TEXT,
  volunteer_age_profile_ar               TEXT,
  volunteer_skills_knowledge             TEXT,
  volunteer_skills_knowledge_ar          TEXT,
  people_volunteers_extra_description    TEXT,
  people_volunteers_extra_description_ar TEXT,
  timeline_target                        VARCHAR(255),
  timeline_target_ar                     VARCHAR(255),
  contact_person_name                    VARCHAR(255),
  contact_person_name_ar                 VARCHAR(255),
  contact_phone                          VARCHAR(32),
  contact_email                          VARCHAR(255),
  other_notes                            TEXT,
  other_notes_ar                         TEXT,
  status                                 VARCHAR(32) NOT NULL DEFAULT 'submitted',
  like_count                             INTEGER NOT NULL DEFAULT 0,
  comment_count                          INTEGER NOT NULL DEFAULT 0,
  created_at                             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_bpr_user_status ON beneficiary_project_requests(user_id, status);
CREATE INDEX idx_bpr_updated_at ON beneficiary_project_requests(updated_at);

-- ============================================================
-- beneficiary_project_request_comments  (FK -> requests, users, self)
-- ============================================================
CREATE TABLE beneficiary_project_request_comments (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_request_id  BIGINT NOT NULL,
  user_id             INTEGER NOT NULL,
  parent_comment_id   BIGINT,
  body                TEXT NOT NULL,
  is_deleted          SMALLINT NOT NULL DEFAULT 0,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bpr_comments_request FOREIGN KEY (project_request_id)
    REFERENCES beneficiary_project_requests(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_bpr_comments_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_bpr_comments_parent FOREIGN KEY (parent_comment_id)
    REFERENCES beneficiary_project_request_comments(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_comments_request ON beneficiary_project_request_comments(project_request_id);
CREATE INDEX idx_comments_user ON beneficiary_project_request_comments(user_id);
CREATE INDEX idx_comments_parent ON beneficiary_project_request_comments(parent_comment_id);

-- ============================================================
-- beneficiary_project_request_likes  (FK -> requests, users)
-- ============================================================
CREATE TABLE beneficiary_project_request_likes (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_request_id  BIGINT NOT NULL,
  user_id             INTEGER NOT NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_request_like_user UNIQUE (project_request_id, user_id),
  CONSTRAINT fk_bpr_likes_request FOREIGN KEY (project_request_id)
    REFERENCES beneficiary_project_requests(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_bpr_likes_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_likes_request ON beneficiary_project_request_likes(project_request_id);
CREATE INDEX idx_likes_user ON beneficiary_project_request_likes(user_id);

-- ============================================================
-- campaigns
-- ============================================================
CREATE TABLE campaigns (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR(200) NOT NULL,
  title_ar       VARCHAR(200) NOT NULL,
  description    VARCHAR(200) NOT NULL,
  description_ar VARCHAR(200) NOT NULL,
  address        VARCHAR(200) NOT NULL,
  beneficiaries  VARCHAR(200) NOT NULL,
  goal_amount    VARCHAR(200) NOT NULL,
  raised_amount  VARCHAR(200) NOT NULL
);

-- ============================================================
-- campaigns_category
-- ============================================================
CREATE TABLE campaigns_category (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_en VARCHAR(200) NOT NULL,
  category_ar VARCHAR(200) NOT NULL
);

-- ============================================================
-- campaings_datas  (note: original table name has a typo, kept as-is)
-- ============================================================
CREATE TABLE campaings_datas (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL,
  liked      INTEGER NOT NULL,
  comment    INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- city_directory_entries
-- ============================================================
CREATE TABLE city_directory_entries (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(255) NOT NULL,
  name_ar         VARCHAR(255),
  category        VARCHAR(128) NOT NULL,
  city            VARCHAR(128),
  address         TEXT,
  phone           VARCHAR(64),
  email           VARCHAR(255),
  website         VARCHAR(500),
  description     TEXT,
  description_ar  TEXT,
  latitude        NUMERIC(10,7),
  longitude       NUMERIC(10,7),
  status          VARCHAR(16) NOT NULL DEFAULT 'approved'
                   CHECK (status IN ('pending','approved','rejected','hidden')),
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_city_directory_category_city ON city_directory_entries(category, city);
CREATE INDEX idx_city_directory_status ON city_directory_entries(status);

-- ============================================================
-- donations
-- ============================================================
CREATE TABLE donations (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_number   VARCHAR(64),
  user_id            INTEGER NOT NULL,
  campaign_id        INTEGER,
  donation_kind      VARCHAR(20) NOT NULL DEFAULT 'campaign'
                      CHECK (donation_kind IN ('general','campaign','sponsorship','in_kind','operational')),
  is_recurring       SMALLINT NOT NULL DEFAULT 0,
  recurring_interval VARCHAR(16) NOT NULL DEFAULT 'none'
                      CHECK (recurring_interval IN ('none','weekly','monthly','quarterly','yearly')),
  message            TEXT NOT NULL,
  amount             VARCHAR(200) NOT NULL,
  payment_status     INTEGER NOT NULL DEFAULT 2,
  delivery_status    VARCHAR(20) NOT NULL DEFAULT 'registered'
                      CHECK (delivery_status IN ('registered','received','under_review','delivered','cancelled')),
  payment_method     VARCHAR(200) NOT NULL,
  impact_note        TEXT,
  transaction_date   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- financial_expenses
-- ============================================================
CREATE TABLE financial_expenses (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_type                VARCHAR(32) NOT NULL DEFAULT 'other'
                               CHECK (expense_type IN ('beneficiary_assistance','operational','administrative','campaign','other')),
  related_case_id             BIGINT,
  related_project_request_id  BIGINT,
  amount                      NUMERIC(14,2) NOT NULL,
  currency                    CHAR(3) NOT NULL DEFAULT 'IQD',
  description                 TEXT,
  expense_date                DATE NOT NULL,
  created_by_user_id          INTEGER,
  created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_financial_expenses_type_date ON financial_expenses(expense_type, expense_date);
CREATE INDEX idx_financial_expenses_case ON financial_expenses(related_case_id);
CREATE INDEX idx_financial_expenses_project ON financial_expenses(related_project_request_id);

-- ============================================================
-- in_kind_donations
-- ============================================================
CREATE TABLE in_kind_donations (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_user_id   INTEGER,
  category        VARCHAR(128) NOT NULL,
  item_name       VARCHAR(255) NOT NULL,
  quantity        VARCHAR(128),
  condition_note  VARCHAR(255),
  pickup_address  TEXT,
  status          VARCHAR(16) NOT NULL DEFAULT 'submitted'
                   CHECK (status IN ('submitted','scheduled','received','delivered','cancelled')),
  notes           TEXT,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_in_kind_donations_donor ON in_kind_donations(donor_user_id);
CREATE INDEX idx_in_kind_donations_status ON in_kind_donations(status);

-- ============================================================
-- marketplace_orders
-- ============================================================
CREATE TABLE marketplace_orders (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    BIGINT NOT NULL,
  buyer_user_id INTEGER,
  quantity      INTEGER NOT NULL DEFAULT 1,
  total_amount  NUMERIC(14,2) NOT NULL DEFAULT 0.00,
  currency      CHAR(3) NOT NULL DEFAULT 'IQD',
  status        VARCHAR(20) NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','approved','processing','completed','cancelled')),
  buyer_note    TEXT,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_marketplace_orders_product ON marketplace_orders(product_id);
CREATE INDEX idx_marketplace_orders_buyer ON marketplace_orders(buyer_user_id);
CREATE INDEX idx_marketplace_orders_status ON marketplace_orders(status);

-- ============================================================
-- marketplace_products
-- ============================================================
CREATE TABLE marketplace_products (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_user_id      INTEGER,
  beneficiary_case_id BIGINT,
  name                VARCHAR(255) NOT NULL,
  name_ar             VARCHAR(255),
  description         TEXT,
  description_ar      TEXT,
  category            VARCHAR(128),
  price               NUMERIC(14,2) NOT NULL DEFAULT 0.00,
  currency            CHAR(3) NOT NULL DEFAULT 'IQD',
  image_path          VARCHAR(500),
  stock_quantity      INTEGER,
  status              VARCHAR(16) NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('draft','pending','approved','rejected','sold_out','hidden')),
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_marketplace_products_seller ON marketplace_products(seller_user_id);
CREATE INDEX idx_marketplace_products_case ON marketplace_products(beneficiary_case_id);
CREATE INDEX idx_marketplace_products_status ON marketplace_products(status);

-- ============================================================
-- marriage_profiles
-- ============================================================
CREATE TABLE marriage_profiles (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             INTEGER NOT NULL,
  profile_code        VARCHAR(64) NOT NULL UNIQUE,
  gender              VARCHAR(64),
  age                 INTEGER,
  city                VARCHAR(128),
  social_summary      TEXT,
  private_notes       TEXT,
  visibility_level    VARCHAR(32) NOT NULL DEFAULT 'employee_only'
                       CHECK (visibility_level IN ('private','employee_only','matched_summary')),
  subscription_status VARCHAR(16) NOT NULL DEFAULT 'free'
                       CHECK (subscription_status IN ('free','paid','waived')),
  status              VARCHAR(20) NOT NULL DEFAULT 'submitted'
                       CHECK (status IN ('submitted','under_review','active','paused','matched','rejected','closed')),
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_marriage_profiles_user ON marriage_profiles(user_id);
CREATE INDEX idx_marriage_profiles_status ON marriage_profiles(status);

-- ============================================================
-- media_posts
-- ============================================================
CREATE TABLE media_posts (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title               VARCHAR(255) NOT NULL,
  title_ar            VARCHAR(255),
  body                TEXT,
  body_ar             TEXT,
  post_type           VARCHAR(16) NOT NULL DEFAULT 'news'
                       CHECK (post_type IN ('news','activity','event','article','video')),
  media_url           VARCHAR(500),
  link_url            VARCHAR(500),
  event_date          DATE,
  status              VARCHAR(16) NOT NULL DEFAULT 'published'
                       CHECK (status IN ('draft','published','hidden')),
  created_by_user_id  INTEGER,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_media_posts_type_status ON media_posts(post_type, status);
CREATE INDEX idx_media_posts_event_date ON media_posts(event_date);

-- ============================================================
-- partners
-- ============================================================
CREATE TABLE partners (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(255) NOT NULL,
  name_ar         VARCHAR(255),
  partner_type    VARCHAR(128),
  contact_phone   VARCHAR(64),
  website         VARCHAR(500),
  description     TEXT,
  description_ar  TEXT,
  logo_path       VARCHAR(500),
  status          VARCHAR(16) NOT NULL DEFAULT 'active'
                   CHECK (status IN ('pending','active','hidden')),
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_partners_status ON partners(status);
CREATE INDEX idx_partners_type ON partners(partner_type);

-- ============================================================
-- sponsorships
-- ============================================================
CREATE TABLE sponsorships (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_user_id       INTEGER,
  beneficiary_case_id BIGINT,
  project_request_id  BIGINT,
  sponsorship_type    VARCHAR(128) NOT NULL,
  amount              NUMERIC(14,2) NOT NULL DEFAULT 0.00,
  currency            CHAR(3) NOT NULL DEFAULT 'IQD',
  schedule_interval   VARCHAR(16) NOT NULL DEFAULT 'monthly'
                       CHECK (schedule_interval IN ('weekly','monthly','quarterly','yearly')),
  next_due_date       DATE,
  status              VARCHAR(16) NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','active','paused','delayed','stopped','completed','cancelled')),
  notes               TEXT,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sponsorships_donor ON sponsorships(donor_user_id);
CREATE INDEX idx_sponsorships_case ON sponsorships(beneficiary_case_id);
CREATE INDEX idx_sponsorships_project ON sponsorships(project_request_id);
CREATE INDEX idx_sponsorships_status_due ON sponsorships(status, next_due_date);

-- ============================================================
-- support_tickets
-- ============================================================
CREATE TABLE support_tickets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER,
  subject     VARCHAR(255) NOT NULL,
  message     TEXT NOT NULL,
  status      VARCHAR(16) NOT NULL DEFAULT 'open'
               CHECK (status IN ('open','in_progress','resolved','closed')),
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_support_tickets_user ON support_tickets(user_id);
CREATE INDEX idx_support_tickets_status ON support_tickets(status);

-- ============================================================
-- user_device_tokens
-- ============================================================
CREATE TABLE user_device_tokens (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL,
  role_id       INTEGER,
  device_token  VARCHAR(512) NOT NULL,
  platform      VARCHAR(32),
  device_id     VARCHAR(128),
  app_version   VARCHAR(64),
  is_active     SMALLINT NOT NULL DEFAULT 1,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_device_token UNIQUE (user_id, device_token)
);
CREATE INDEX idx_user_device_tokens_user ON user_device_tokens(user_id);
CREATE INDEX idx_user_device_tokens_role ON user_device_tokens(role_id);
CREATE INDEX idx_user_device_tokens_active ON user_device_tokens(is_active);

-- ============================================================
-- user_profile_audit_logs
-- ============================================================
CREATE TABLE user_profile_audit_logs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER NOT NULL,
  actor_source   VARCHAR(32) NOT NULL DEFAULT 'user',
  actor_user_id  INTEGER,
  changed_field  VARCHAR(64) NOT NULL,
  old_value      TEXT,
  new_value      TEXT,
  metadata_json  TEXT,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_profile_audit_logs_user ON user_profile_audit_logs(user_id);
CREATE INDEX idx_user_profile_audit_logs_field ON user_profile_audit_logs(changed_field);
CREATE INDEX idx_user_profile_audit_logs_created ON user_profile_audit_logs(created_at);

-- ============================================================
-- user_profiles
-- ============================================================
CREATE TABLE user_profiles (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL,
  full_name       VARCHAR(200) NOT NULL,
  gender          VARCHAR(200) NOT NULL,
  address         VARCHAR(200) NOT NULL,
  profile_picture VARCHAR(200) NOT NULL DEFAULT '0'
);

-- ============================================================
-- volunteer_applications
-- ============================================================
CREATE TABLE volunteer_applications (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER,
  full_name     VARCHAR(255) NOT NULL,
  phone         VARCHAR(64),
  city          VARCHAR(128),
  skills        TEXT,
  experience    TEXT,
  availability  TEXT,
  status        VARCHAR(16) NOT NULL DEFAULT 'submitted'
                 CHECK (status IN ('submitted','approved','rejected','inactive')),
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_volunteer_applications_user ON volunteer_applications(user_id);
CREATE INDEX idx_volunteer_applications_status ON volunteer_applications(status);

-- ============================================================
-- volunteer_missions
-- ============================================================
CREATE TABLE volunteer_missions (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              VARCHAR(255) NOT NULL,
  title_ar           VARCHAR(255),
  description        TEXT,
  description_ar     TEXT,
  city               VARCHAR(128),
  mission_date       DATE,
  needed_volunteers  INTEGER,
  status             VARCHAR(16) NOT NULL DEFAULT 'open'
                      CHECK (status IN ('draft','open','closed','completed','cancelled')),
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_volunteer_missions_status_date ON volunteer_missions(status, mission_date);

-- ============================================================
-- volunteer_mission_signups
-- ============================================================
CREATE TABLE volunteer_mission_signups (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER NOT NULL,
  mission_id     BIGINT NOT NULL,
  status         VARCHAR(16) NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected','joined','cancelled','completed')),
  notes          TEXT,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  checked_in_at  TIMESTAMP,
  completed_at   TIMESTAMP,
  hours_served   NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  CONSTRAINT uq_volunteer_mission_signups_user_mission UNIQUE (user_id, mission_id)
);
CREATE INDEX idx_volunteer_mission_signups_user ON volunteer_mission_signups(user_id);
CREATE INDEX idx_volunteer_mission_signups_mission ON volunteer_mission_signups(mission_id);
CREATE INDEX idx_volunteer_mission_signups_status ON volunteer_mission_signups(status);

-- ============================================================
-- updated_at triggers (replaces MySQL "ON UPDATE CURRENT_TIMESTAMP")
-- ============================================================
CREATE TRIGGER trg_app_notification_devices_updated_at BEFORE UPDATE ON app_notification_devices FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_beneficiary_cases_updated_at BEFORE UPDATE ON beneficiary_cases FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_beneficiary_project_requests_updated_at BEFORE UPDATE ON beneficiary_project_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_beneficiary_project_request_comments_updated_at BEFORE UPDATE ON beneficiary_project_request_comments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_city_directory_entries_updated_at BEFORE UPDATE ON city_directory_entries FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_in_kind_donations_updated_at BEFORE UPDATE ON in_kind_donations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_marketplace_orders_updated_at BEFORE UPDATE ON marketplace_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_marketplace_products_updated_at BEFORE UPDATE ON marketplace_products FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_marriage_profiles_updated_at BEFORE UPDATE ON marriage_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_media_posts_updated_at BEFORE UPDATE ON media_posts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_partners_updated_at BEFORE UPDATE ON partners FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sponsorships_updated_at BEFORE UPDATE ON sponsorships FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_support_tickets_updated_at BEFORE UPDATE ON support_tickets FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_device_tokens_updated_at BEFORE UPDATE ON user_device_tokens FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_volunteer_applications_updated_at BEFORE UPDATE ON volunteer_applications FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_volunteer_missions_updated_at BEFORE UPDATE ON volunteer_missions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_volunteer_mission_signups_updated_at BEFORE UPDATE ON volunteer_mission_signups FOR EACH ROW EXECUTE FUNCTION set_updated_at();
